### ISSUE TITLE
Add checkbox to page properties (disable parsing)

### ISSUE THREAD

**Issue by criwe** [featdd/dpn_glossary#100]
Hi!
It Would be nice to have a checkbox in the page properties to exclude that pages from parsing.
You can exclude pages via constant editor allready, but when added to page propertiert even editors could be able to set this.
Thx!
Best
Christoph

**Comment by featdd** [comment]
That should be possible, have it on my to list now.
Just let me find some time 😅

**Comment by featdd** [comment]
@criwe 

I just forgot that I implemented this in the base functionality already.
No checkboxes but in typoscript you can add page ids comma seperatly to be excluded.

see in the [documentation](https://docs.typo3.org/typo3cms/extensions/dpn_glossary/Configuration/ExtensionSettings/Index.html) (settings.parsingExcludePidList)

**Comment by criwe** [comment]
@featdd 
Yep, I know :-)
"Problem": an editor has no way to exclude pages and has to bother the admin
Best,
Christoph
