### ISSUE TITLE
Typo in pathname to ContentElementWizard.t3s

### ISSUE THREAD

**Issue by sterborg** [featdd/dpn_glossary#101]
In ext_tables the path to the file spells the folder "TSConfig" with a big "C". The folder itself is spelled "TSconfig" with a small "c". This leads to an error "File "EXT:dpn_glossary/Configuration/TSConfig/ContentElementWizard.t3s" was not found."

**Comment by featdd** [comment]
Oh, a disadvantage when you test on a case insensitive file system 😅 
will take care of it

**Comment by featdd** [comment]
solved in cfd85a8d8d9b19c0e58e010a73d93ad0d1a425f5
