### ISSUE TITLE
Uncaught TYPO3 Exception

### ISSUE THREAD

**Issue by Hogego** [featdd/dpn_glossary#102]
Hello, 
I´m using version 2.7.3. with TYPO3 7.6.22
Clicking on a link fpr the detail-view (witch I placed on another side an configured the UID in the ts-setup) I get an Exception Error I don't understand:
sys: #1313855175: The action "show" (controller "Term") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php. (More information)
Thank´s a lot for help

**Comment by featdd** [comment]
Hi this is new to me, did you try to deactivate and reactivate the extension?
Also clear all caches (install tool etc.)

**Comment by Hogego** [comment]
Hi, did what you told me. Nothing changed:
Do you have any other idea?

Uncaught TYPO3 Exception
#1313855175: The action "show" (controller "Term") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php. (More information)
TYPO3\CMS\Extbase\Mvc\Exception\InvalidActionNameException thrown in file
../typo3_src-7.6.22/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php in line 250.

**Comment by featdd** [comment]
have you added the plugin in the backend or over TypoScript?

**Comment by Hogego** [comment]
I have installed the plugin via the extension manager and than inserted the static template

**Comment by Hogego** [comment]
Hello again,

• I´ve tried to install the plugin in another installation and there everything works fine.

• I´ve tried to deinstall the glossary cleared the caches and everything and installed it again
• I´ve tried to deinstall other extensions 
but nothing changed
• Now when I put the detail-view on the same page as the list-view I get this error:
Required argument "term" is not set for Featdd\DpnGlossary\Controller\TermController->show

still searching …

**Comment by featdd** [comment]
@Hogego the detail plugin always has to be on a seperate page, for it needs a term to display, otherwise you have to catch it as a 404
