### ISSUE TITLE
Missing git tags for 2.7.2 and 2.7.3

### ISSUE THREAD

**Issue by baschny** [featdd/dpn_glossary#103]
Hi,

you missed to add the git tags to 2.7.2 and 2.7.3 which is probably why they do not show up in https://packagist.org/packages/featdd/dpn-glossary and why the latest version that is installable with `"featdd/dpn-glossary": "^2.7.0"` is 2.7.1.

Would you mind adding those tags and making sure it gets updated on packagist? Thanks a lot!

Kind regards,
Ernesto

**Comment by featdd** [comment]
Hi,

sorry for that, added them now.

Greetings
Daniel
