### ISSUE TITLE
Uppercase Lowercase

### ISSUE THREAD

**Issue by bpAfm** [featdd/dpn_glossary#109]
The Extension doesn`t distinguish between Uppercase and Lowercase.
Example:
i have an Acronym "AIMS" and on the Page something like this:
The Natural Products session aims to provide ....

For the Extension "aims" is the same as "AIMS".

In the Database tx_dpnglossary_domain_model_term.name is binary. If i set this Select

`select name from `tx_dpnglossary_domain_model_term` where name LIKE "%aims%"`

no Result as expected.

This Select

`select name from `tx_dpnglossary_domain_model_term` where name LIKE "%AIMS%"`

this gives me the correct Record.

Typo3 8.7.8
dpn_glossary 2.7.3

Could anybody confirm my Issue?

Best

Bernd Pier

**Comment by featdd** [comment]
Hi @bpAfm,

the parser works case insensitive, but adding an option in terms to be explicit case sensitive would be easy to implement.

**Comment by bpAfm** [comment]
Hi featdd,

would you implement this?

**Comment by featdd** [comment]
I can, just let me find the time

**Comment by featdd** [comment]
solved in faf68215558540f5d6b65113cacac87313fa7e0c
