### ISSUE TITLE
Migrate to TYPO3 9.x and PHP 7.2

### ISSUE THREAD

**Issue by nozdrin-brd** [featdd/dpn_glossary#112]
TYPO3 9.x has been released. Typo3 community is looking forward for LTS release. Thus there is a question if dpn_glossary will be migrated too

**Comment by featdd** [comment]
Yes, the update will need some refactoring work but it is on my to do list.
I'll wait till the LTS is released to prevent the multiple adjustments for compatibility.

Greetings
Daniel

**Comment by nicozerr** [comment]
Hi.
Can you confirm the current state of the migration ?
Best regards.

**Comment by featdd** [comment]
Hi @nicozerr @dnozdrin 

last weekend I took some time to upgrade the extension, see [typo3_9_compatibility](https://github.com/featdd/dpn_glossary/tree/typo3_9_compatibility).

Everything seems to work properly, but I will wait till lts release.
I want to add the a not yet implemented slug feature etc.

If you want to test the current state feel free to do so 😃 

Greetings
Daniel
