### ISSUE TITLE
Parser - Case sensitive

### ISSUE THREAD

**Issue by GuillaumeGBzh** [featdd/dpn_glossary#113]
Hello,

Thank you for developing this extension. A beautiful discovery!

I use parser to display a tooltip relative to the terms of my glossary.
However, the tooltip appears too often because the parser is case-sensitive.

For example, I have a term "DES".
In my FR texts, "Des" displays a tooltip. Which is problematic because it is not the same meaning.

You can fix this?

Thanks.

**Comment by featdd** [comment]
this was already asked in #109 
it is solved in faf68215558540f5d6b65113cacac87313fa7e0c and will be available in the next update

**Comment by featdd** [comment]
I'll try to upload a release this weekend

**Comment by featdd** [comment]
Update 2.7.4 was pushed right now
