### ISSUE TITLE
Using with fluidtypo3 (flux, fluidcontent)

### ISSUE THREAD

**Issue by MrMooky** [featdd/dpn_glossary#119]
dpn_glossary does not seem to work with Flux and/or Fluidcontent extensions. Is there any way to enable support, or is it technically not possible due to the flexform xml structure?

**Comment by featdd** [comment]
Hi @MrMooky,

that should not be the problem, the parser is working with the final rendered markup.
So it does'nt care about the extensions you used before.

Maybe you have missed something in your configuration, did you set the storagePid?
Did you've taken a look in the [documentation](https://docs.typo3.org/typo3cms/extensions/dpn_glossary/) yet?

Greetings
Daniel

**Comment by MrMooky** [comment]
Hello @featdd,

yes, I always read the docs first if something does not work. :)

The first element is a basic TYPO3 Text, the second is a custom Fluidcontent element (accordion). As you can see, "NBA" should have a title tag applied to it, but it does not within the accordion.

![screen shot 2018-08-10 at 9 00 50 am](https://user-images.githubusercontent.com/3603346/43943523-2b08d47c-9c7c-11e8-9e00-52af670c5ece.png)

**Comment by MrMooky** [comment]
Update: It is actually the bold text. If I set the first "NBA" bold, the title won't be outputted. Is this a bug, or expected behavior?

**Comment by featdd** [comment]
did you add the "b"-Tag to the allowed parsing tags?

The tags which should be parsed are explicit configured, by default only paragraphs are parsed and any child elements ignored.

Greetings
Daniel

**Comment by MrMooky** [comment]
Sorry, my bad. Had b and i, but needed strong and em. Works just fine. Thanks.

**Comment by featdd** [comment]
Glad I could help, have a nice weekend
