### ISSUE TITLE
Checking if element is children of a forbidden parent does not match

### ISSUE THREAD

**Issue by julianhofmann** [featdd/dpn_glossary#122]
Current check: `if (false === in_array($parentTags, $forbiddenParentTags, true)) {` - but both variables are arrays. 

If the check should work like described in constants ("Tags which are not allowed as **direct** parent for a parsingTag"), it should look like this:
`if (false === in_array($parentTags[count($parentTags)], $forbiddenParentTags, true)) {`

If the check should check against **any** parentTag, you would need somethings like:
`if (false === !!array_intersect($parentTags, $forbiddenParentTags)) {`
(https://stackoverflow.com/questions/7542694/in-array-multiple-values#answer-11040612)

**Comment by MalathDaThon** [comment]
perfect! thanks julian, second part (any parent tag) helped me a lot!

would be nice to have this feature for "any parent class/id" 
so you could exclude whole parts of your layout from parsing...

**Comment by featdd** [comment]
I'll try to refactor this feature to be more flexible, with classes ids and so on.

Thanks for your fix

**Comment by featdd** [comment]
solved in 14d7b634b2f27de61fabc45ed166645fca692912
