### ISSUE TITLE
TCA Migrations showitem text, sys_language_uid

### ISSUE THREAD

**Issue by Prizzler** [featdd/dpn_glossary#123]
Hi,

currently i migrate my typo3 system from version 7 to 8.7. I am using typo3 v8.7.19 and dpn_glossary v2.7.5. On the install tab under "TCA Migrations" i get the following hints:

- "The 4th parameter 'specConf' of the field 'showitem' with fieldName = 'text' has been migrated, from TCA table "tx_dpnglossary_domain_model_description['types']['1']['showitem']"to "tx_dpnglossary_domain_model_description['types']['1']['columnsOverrides']['text']['defaultExtras']"

- "The 4th parameter 'specConf' of the field 'showitem' with fieldName = 'sys_language_uid' has been migrated, from TCA table "tx_dpnglossary_domain_model_term['types']['1']['showitem']"to "tx_dpnglossary_domain_model_term['types']['1']['columnsOverrides']['sys_language_uid']['defaultExtras']"

cheers P.

**Comment by featdd** [comment]
hi @Prizzler,

thanks for the hint, I already did this migrations in the compatibility branch for 9.x
the new version will have a 9.5 dependency.

for now I would keep the tca as it is as its still working and only deprecated, so it will still work with 7.6.

greetings
Daniel
