### ISSUE TITLE
exclude content inside div by class/id from parsing

### ISSUE THREAD

**Issue by MalathDaThon** [featdd/dpn_glossary#124]
something for the "nice to have wish-list":

it would be great to have a function to exclude the whole content inside a `<div></div>` from parsing by id or class. 
so it would be easier to exclude parts of a website from parsing. 

Kind regards, Malath

**Comment by featdd** [comment]
hi @MalathDaThon,

you can achieve this via the typoscript settings "forbiddenParentTags" & "forbiddenParsingTagClasses"

Greetings
Daniel

**Comment by jokumer** [comment]
MalathDaThon means "**whole** content inside a `<div></div>` from parsing **by id or class**".
The "forbiddenParentTags" requires, you only use this tag for glossary exclusion functionality - which is contrary the idea of hypertext markup language .
The "forbiddenParsingTagClasses" requires, you set this class in each child element tag, which is nearly impossible with RTE generated content from the content management system.
I will go with MalathDaThon, and ask to reopen this issue to feature **exclusion from parsing by id or class**.
It is just a feature request.

**Comment by featdd** [comment]
I will make some tests and try to find the time to implement this, thanks for the clarification

**Comment by featdd** [comment]
Hi @MalathDaThon @jokumer,

this has been implemented here: a6a553b50e5105b37ca7e31c83fb93b02cb83edb

Greetings
Daniel
