### ISSUE TITLE
[Deprecation] parsing of terms not working with cached pages

### ISSUE THREAD

**Issue by rr-it** [featdd/dpn_glossary#125]
The parsing of terms is broken by commit https://github.com/featdd/dpn_glossary/commit/3907441377fc5ebb631fac40bcb5d2c381f7a1e4 .

On first page load terms are correctly parsed and replaced. On second page load - this time as cached page by TYPO3 - none of the terms are replaced.

TYPO3: v7.6.31
dpn_glossary: v2.7.5

**Comment by featdd** [comment]
There seems different beheviour in typo3 versions and setup, in 8.7.x it didn't.

Had fixed this for 9 compatibility, could you test if [this](https://github.com/featdd/dpn_glossary/commit/5b1080c5b8d8cbe3c48d5c11f9f025593ad80ef3) is also valid for 7.6?

greetings
Daniel

**Comment by featdd** [comment]
hi @rr-it thanks for testing, guess I'll cherry pick this and push this into the next update.

**Comment by featdd** [comment]
merged into master 27682036c7c40dc4e1ccab7bff8273d69c0a92f1
