### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ABooooo** [featdd/dpn_glossary#128]
Hi, admin part of documentation is totally useless. For someone who wants to start with your plugin is not clear how to start, how to create pages, content, links, etc... I hope you are still working on this part and that it will soon be available. Thanks!

**Comment by featdd** [comment]
Hi @ABooooo,

The administrator part implies knowledge of a integrator or developer, it's short I agree but not necessarily useless.

You only need to create a page for the detailplugin, or listplugin too if you use <3.0.0 and reference the detailpage as also the storagePid in your typoscript constants.

This has to be done so the parser knows which storage to use and what page to link the terms to.

Terms itself are just records stored in a storage folder.

Maybe you can help me and tell me how much details you would need, I admit that I'm not that good at writing user documentation :-D

**Comment by ABooooo** [comment]
Hi, ok, we tried one more time. It looks like we are not that good in Typo3 as we thought. :D 
We have a few points that we are missing in the documentation. It is but just our opinion. 

_2. Add the static TypoScript to your Site template_
What exactly has to be added? Example? Is to be find under Configuration Reference?

_3. Create a page for terms_
How do you get input fields as shown in screenshot? How do you create links? How does a detail page looks like?

My suggestion would be, to create a simple and short video tutorial. It doesn't even have to include an audio. Just a quick example from configuration to real-time example. That shouldn't take you a lot of time and would be very helpful. 

Thanks!

**Comment by TimKraemer** [comment]
Congrats on closing this issue without actually fixing anything. I'm feeling the same way as @ABooooo - without you comment "Terms itself are just records stored in a storage folder" I would have never got that part running.

**Comment by featdd** [comment]
Hi @TimKraemer,

sorry you got a bit frustated configuring the extension.
I will re-evaluate this and try to write some further explanations for this part of the documentation.

Hope the explenation in the [comment](#128#issuecomment-433879855) gave you the help you needed for now.

Greetings
Daniel

**Comment by TimKraemer** [comment]
Thanks for responding so quickly! I will hijack this issue a bit to explain my frustration.
First what I done to get it somewhat "running":

**install extension**
1. Admin Tools -> Extensions -> top left drop-down -> get extensions -> search for "glossary" -> click cloud-arrow icon "import and install" left to "dreipunktull Glossar" extension

**create a "folder" for your glossary-terms**
2. Switch to Web -> List -> Create a new folder (e.g. drag and drop the folder symbol from toolbar into your page-tree)
3. Add a new record (by clicking the + icon) - choose "# Term" from "3.0 dreipunktnull Glossar"
4. Fill out a first term

**configure extension to tell it where the terms will be**
5. find the "page-id" or pid of your folder created in step 2 (e.g. by clicking on it, look at "Path" upper right corner it's the number in brackets after your folder-name e.g. `[123]`
6. Switch to Web -> Template -> Select the site you want to activate a glossary for -> top right drop-down -> Constant Editor ->  Select Category "DPN_GLOSSARY" -> scroll down to section "Others" fill in your page-id number from step 5.

**create a "glossary" overview page for your website**
7. Switch to Web -> Page -> Create a new Page (e.g. drag and drop the page symbol (named "standard" for some reason) into your page-tree.
8. Add a new record (by clicking the + icon) - choose "Page Content" -> in the new window, select Content Element type "Insert Plugin" (you find it at the bottom of the drop-down in section "special" -> accept the refresh -> switch to tab "Plugin" and select plugin "Glossary" from drop-down -> accept the refresh -> search the record storage page (which is your folder set up in step 2) -> save your changes.

I acknowledge that most of those ridiculous complicated steps are Typo3's fault, but still the extension is lacking a lot of documentation....

Now having done those steps, adding an acronym "test" with a definition "long test definition" and css-popup "popup test", the extension seems to replace the terms on some pages (not all of them) with an `<acronym title="test" lang="">test</acronym>` tag - which unfortunately only shows the same term in its mouse-over popup - so far so useless - After changing it to be an "Abbreviation" it uses the css tooltip. However this takes a long time until it happens, which might be a caching thing or it just takes some long time to process all sites - I don't know.

Again this is lacking what any of those fields are doing (maybe show some examples?) 
* when is the css tooltip used?
* when and where is the description shown?

**Comment by GQDeltex** [comment]
@TimKraemer Great Explanation! Thanks.
I have one addition to step 6:
6b. If you cannot find "DPN_GLOSSARY" under "Constant Editor", select "Info/Modify" instead and click on "Edit the whole template record". Once there, navigate to "Includes" and select "dpn_glossary" from the list on the right ("Available Items") and add it to the left ("Selected Items") list. Now save, close and try step 6 again.

**Comment by featdd** [comment]
Hi @TimKraemer, @ABooooo 

sorry for this late response, I adjusted the documentation a bit, will try to work on it some more the next days.

But while I will try to have enough information to use the extension I'll still refuse to explain basic TYPO3 knowledge (using the template module and so on...) as this should **not** be a part of an extension only documentation.

Greetings
Daniel

**Comment by featdd** [comment]
I reworked the documentation a bit and added some details.

You may have a look at the main branch here: https://docs.typo3.org/p/featdd/dpn-glossary/main/en-us/

I'll close this for now.

Greetings
Daniel

**Comment by fgerards** [comment]
can we split list/detail view ? our layout/design requires, that list view and detail view have completely different, editable surrounding areas (list-> header-image, detail->no header -image etc.)
