### ISSUE TITLE
 Glossary RealURL paths stopped working after TYPO3 and module Update

### ISSUE THREAD

**Issue by Scopestyle** [featdd/dpn_glossary#129]
**Problem**

We updated our TYPO3 installation from 7 to 8, and updated the `dpn_glossary` extension from `2.6.13` to `2.7.5`.  We are having the issue that `RealURL 2.2.1` stopped working for the extension, in the sense that URLs are being generated as if RealURL were disabled for these pages. 

	/?tx_dpnglossary_glossarydetail%5Bterm%5D=31&tx_dpnglossary_glossarydetail%5Baction%5D=show&tx_dpnglossary_glossarydetail%5Bcontroller%5D=Term&cHash=614c2f3c0215b625e270efbe28cd7173

_Instead of_

	/detail/name-of-detail-object/

Other extensions, like News, and the standard pages in the website work just fine. 

I would like to know if there anything changed should be looking out for, or what we're doing wrong trying to get RealURL to work with the module. Is there a sample RealURL configuration for dpn_glossary somewhere that works with TYPO3 8?

**Code**

Here is an example setup what we currently have (with non-dpn glossary parts removed)

	<?php 

	$RootPID = array(
		'domain1.de' => '1',
		'domain2.de' => '166',
		'domain3.de' => '258',
	);

	$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT'] = array(
		'init' => array(
			'enableCHashCache' => true,
			'enableUrlDecodeCache' => true,
			'enableUrlEncodeCache' => true,
			'appendMissingSlash' => 'ifNotFile,redirect[301]', 
		),
		'redirects' => array(),
		'preVars' => array(
			array('GETvar' => 'L','valueMap' => array('en' => '1', 'fr' => '2', 'es' => '3', 'pl' => '4', 'ru' => '5', 'nl' => '6'), 'noMatch' => 'bypass'),
			array(
				'GETvar' => 'no_cache',
				'valueMap' => array(
					'nc' => 1,
			 ),
				'noMatch' => 'bypass',
			),
		),
		'pagePath' => array(
			'type' => 'user',
			'userFunc' => 'EXT:realurl/class.tx_realurl_advanced.php:&tx_realurl_advanced->main',
			'spaceCharacter' => '-',
			'languageGetVar' => 'L',
			'expireDays' => 7,
			'disablePathCache' => '1',
			'rootpage_id' => $RootPID[$_SERVER['HTTP_HOST']],
			'postVarSet_failureMode'=>'',
			'firstHitPathCache' => 1,
			'emptyUrlReturnValue' => '/',
		),
		/*** Aussehen der Dateinamen für die verschiedenen PageTypes ***/
		'fileName' => array (
			'defaultToHTMLsuffixOnPrev' => false,
			'index' => array(
				'index.html' => array('keyValues' => array ('type' => 1,),),
				'rss.xml'   => array('keyValues' => array ('type' => 100,),),
				'atom.xml'   => array('keyValues' => array ('type' => 103,),),
				'sitemap.xml'   => array('keyValues' => array ('type' => 776,),),
			),
		),
		'fixedPostVars' => array(
			'dpn_glossary_Glossarylist' . '_list_RealUrlConfig' => array(
				array(
					'GETvar' => 'tx_dpnglossary_glossarylist[controller]',
					'noMatch' => 'bypass'
				),
				array(
					'GETvar' => 'tx_dpnglossary_glossarylist[action]',
					'noMatch' => 'bypass'
				),
				array(
					'GETvar' => 'tx_dpnglossary_glossarylist[@widget_0][character]',
				),
			),
			'dpn_glossary_Glossarydetail' . '_detail_RealUrlConfig' => array(
				array(
					'GETvar' => 'tx_dpnglossary_glossarydetail[controller]',
					'noMatch' => 'bypass'
				),
				array(
					'GETvar' => 'tx_dpnglossary_glossarydetail[action]',
					'noMatch' => 'bypass'
				),
				array(
					'GETvar' => 'tx_dpnglossary_glossarydetail[term]',
					'lookUpTable' => array(
						'table' => 'tx_dpnglossary_domain_model_term',
						'id_field' => 'uid',
						'alias_field' => 'name',
						'addWhereClause' => ' AND NOT deleted',
						'useUniqueCache' => 1,
						'useUniqueCache_conf' => array(
							'strtolower' => 1,
							'spaceCharacter' => '-'
						),
						'languageGetVar' => 'L',
						'languageExceptionUids' => '',
						'languageField' => 'sys_language_uid',
						'transOrigPointerField' => 'l10n_parent',
						'autoUpdate' => 1,
						'expireDays' => 0
					),
				),
				array(
					'GETvar' => 'tx_dpnglossary_glossarydetail[pageUid]'
					),
				),

			// ID

			'252' => 'dpn_glossary_list_RealUrlConfig',
			'253' => 'dpn_glossary_detail_RealUrlConfig',
		),
		'postVarSets' => array(
			'_DEFAULT' => array(
			),
		),
	);

Kind regards,

Erik

**Comment by Scopestyle** [comment]
Just a heads up that a module downgrade to `2.7.3` fixed the problem, and RealURL works again. So I think there might be something wrong in a newer version.

**Comment by featdd** [comment]
In a556944 I changed the behaviour of forcing the configuration to a proper realurl hook.

Did you have included the configuration manually? Otherwise realurl needs to auto generate a configuration with the glossary included.

I tested >2.7.3 and realurl still worked, have you debugged the configuration in runtime?
Or did may did some page ids changed in your upgrade process for whatever reason and the fixedPostvar mapping doesnt match anymore?

**Comment by Scopestyle** [comment]
Hi @featdd Yes the configuration was made manually, I did try to auto generate the realurlconf. But that didn't work (no URL's where generated for `dpn_glossary`), ID's of the pages were all the same, no changes where made.

 Downgrading the module fixed all issues, so a change in ID's couldnt have been a problem. Debug is set currently in the install tool,

**Comment by featdd** [comment]
Hi @Scopestyle 

there is a type in the assignment of the configuration to the page uid.

It should be `dpn_glossary_Glossarylist_list_RealUrlConfig` not `dpn_glossary_list_RealUrlConfig`

Greetings
Daniel
