### ISSUE TITLE
Limit Term per Page

### ISSUE THREAD

**Issue by m03rv** [featdd/dpn_glossary#131]
Hello,
its more a question than a issue, where and how can i setup "settings.maxReplacementPerPage" ?
Im sorry, im very new on typo3...
Best
Marvin

**Comment by featdd** [comment]
Hi

you can achieve this via the template module overwriting the setting or define the constant.
As this is a general question you should rather seek for help in the community.
Sign up for typo3 slack or take a look at the [documentation](https://docs.typo3.org/). 🤓 

Greetings
Daniel
