### ISSUE TITLE
Glossary 3.0 Update?

### ISSUE THREAD

**Issue by Erbse04** [featdd/dpn_glossary#134]
Mega cool would be if the keyword would be linked to a page only once where it happens. On the created glossary page or the link, it would only appear in bold. What do you think of the idea? That would support some of us... Looking forward to here from you

**Comment by featdd** [comment]
Hi @Erbse04 

I'm not sure what you mean...
You can configure the rendering of the links with typoscript and you can configure how many times a term should be replaced.

You could add a typoscript to your glossary page to just wrap the term in a bold tag and so on...

The typoscript integration gives you a great flexibility which should be used for your custom needs.
But the extension itself should be simple in its defaults in my opinion.

Greetings
Daniel

**Comment by Erbse04** [comment]
> Hi @Erbse04
> 
> I'm not sure what you mean...
> You can configure the rendering of the links with typoscript and you can configure how many times a term should be replaced.
> 
> You could add a typoscript to your glossary page to just wrap the term in a bold tag and so on...
> 
> The typoscript integration gives you a great flexibility which should be used for your custom needs.
> But the extension itself should be simple in its defaults in my opinion.
> 
> Greetings
> Daniel

Hi Daniel, thx for these informations... I did not realize that...sorry :) Also THX for this great extension. Best Tim

**Comment by featdd** [comment]
Also I can refer you to the [official documentation](https://docs.typo3.org/typo3cms/extensions/dpn_glossary/)

Have fun with the extension
