### ISSUE TITLE
Bug in multidomainsystem

### ISSUE THREAD

**Issue by criwe** [featdd/dpn_glossary#137]
Hi!
Since Version 2.7.5 (maybe 2.7.4) parsing in an multidomainsystem doesn´t work right in a TYPO3 8.6. 
I didn´t found a clear sytematic, but links apear wrong (i.e. domain 1 where domain 2 should be used).
I´ve made downgrade to 2.7.3 where everything works fine.
Thanks!
Best
Christoph

**Comment by featdd** [comment]
Hi @criwe,

Did you configure the detailpage for both domains properly?

**Comment by criwe** [comment]
Hi @featdd 

a far as i remeber yes (it is a few days away since I´ve tested).
I have in mind that after clearing cache the first domain you call is used by all other domains.

Best,
Christoph

**Comment by featdd** [comment]
Hi @criwe,

I just tested this case, I had two domains and two detailpages under each domain and could'nt reproduce this issue.

Could check again if this is maybe just some configuration problem?

Greetings
Daniel
