### ISSUE TITLE
W3C html validation failure

### ISSUE THREAD

**Issue by freshworkx** [featdd/dpn_glossary#139]
Please merge, tag and release your simple solution from branch 'domHtml5Repairs' (#138) to prevent W3C validation errors on self closing tags, such as `</source> `

**Comment by featdd** [comment]
@freshworkx done, see: a2ce5d5f6cb4928b313a4d68bb72d5c380067d50

will be released soon, sorry for the long delay

**Comment by freshworkx** [comment]
Thanks @featdd last but not least ;-)
Maybe we can get your ext into our next project.
