### ISSUE TITLE
Terms cached and used from wrong domain

### ISSUE THREAD

**Issue by dsteinborn** [featdd/dpn_glossary#141]
When using two domains e.g. example.com and example.org with separate storages the wrong terms will be used for one of the domains.
The terms of the domain called initially after clearing the cache will also be used for the second domain.

Commit https://github.com/featdd/dpn_glossary/commit/1323b51cf2ca98adaf3b561169f0dd9acaeb60c1 fixes this issue but could under rare circumstances lead to duplicate cache identifiers as well.
For example language 1 with storage pid 15 and language 11 with storage pid 5 which will both lead to cache identifier "termsByNameLength115". I would suggest to add an additional separator between language uid and storage pids.

Edit: Another case for duplicate cache identifiers:
- Language 1 and storage pids 11 and 20
- Language 1 and storage pid 1120

**Comment by featdd** [comment]
Hi @dsteinborn,

you're right haven't seen this when adding the storage pids.
An edge case but a case, added a seperator and amended it to the fix, see: 17479983f14e5a0fe86e8c2a97f4702c484f061e

Greetings
Daniel

**Comment by dsteinborn** [comment]
Hi @featdd,

you'll also need a separator for implode to prevent the second case generating duplicate cache identifiers.
