### ISSUE TITLE
on detail page, current character is not highlighted

### ISSUE THREAD

**Issue by dextar47** [featdd/dpn_glossary#151]
isCurrent property remain NULL on detail page of a term.

**Comment by featdd** [comment]
Hi @dextar1,

What do you mean on the detail page?
The pagination is for the list plugin only, the parameters are missing on the detailpage to determine the character...

Could you please explain your issue further or is mine helping you out?

Greetings
Daniel

**Comment by featdd** [comment]
closed due to missing response
