### ISSUE TITLE
Serialization error when writing terms to cf-Table

### ISSUE THREAD

**Issue by sterborg** [featdd/dpn_glossary#153]
When writing the terms to the cf-Table, the terms object is serialized. The subobjects description and synonyms contain error messages:

```
...
s:11:" * synonyms";O:43:"TYPO3\CMS\Extbase\Persistence\ObjectStorage":6:{
			s:52:" TYPO3\CMS\Extbase\Persistence\ObjectStorage warning";s:228:"You should never see this warning. If you do, you probably used PHP array functions like current() on the TYPO3\CMS\Extbase\Persistence\ObjectStorage. To retrieve the first result, you can use the rewind() and current() methods.";
			s:10:" * storage";a:0:{}
			s:13:" * isModified";b:0;
			s:24:" * addedObjectsPositions";a:0:{}
			s:26:" * removedObjectsPositions";a:0:{}
			s:18:" * positionCounter";i:0;
		}
...
```

TYPO3 9.5.15
PHP 7.3

**Comment by featdd** [comment]
Hi @sterborg,

this is a static message of the ObjectStorage, it should work fine or do you have issues in displaying synonyms?

If you use xdebug to view any ObjectStorage during runtime you'll always see this message.

Greetings
Daniel

**Comment by sterborg** [comment]
Hi Daniel,

maybe no special problem with serialization, but since the parser service writes all terms in one cache row the row is becoming quite big. In my special case I got a Doctrine\DBAL\Exception\DriverException "Got a packet bigger than 'max_allowed_packet' bytes. The setting is 1048576.
Is it a good idea to write all terms in one cacheing row btw?

Greetings
Stefan

**Comment by featdd** [comment]
You can optionally disable the cache, with the page cache active there would be no need for it at all.

I should do a necessarity check.

Your error is unknown to me, maybe your settings have a small limit.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @sterborg,

do you still have an issue or questions?
Otherwise I would like to close this issue.

Greetings
Daniel

**Comment by sterborg** [comment]
@featdd no, thank you. Please close the issue.

Greetings
Stefan
