### ISSUE TITLE
Space between two sequent terms not preserved

### ISSUE THREAD

**Issue by loeffe1** [featdd/dpn_glossary#155]
If a text includes two sequent terms as in Term1 Term2, the space between the two terms is removed when the anchors are being added. Is there a way to preserve the space?

**Comment by featdd** [comment]
Hi @loeffe1,

could you give me an example html?

**Comment by featdd** [comment]
Hi @loeffe1,

I could not reproduce this in the latest version, do you have some HTML and term example I could test?

**Comment by featdd** [comment]
Hi @loeffe1,

Is this still an issue?

Greetings
Daniel

**Comment by featdd** [comment]
Closing this due to missing response and reproducability
