### ISSUE TITLE
Unknown type: select, render type: select in Flexform

### ISSUE THREAD

**Issue by Lurchi96** [featdd/dpn_glossary#158]
Missing "renderType" in FlexForm Preview.xml for element "switchableControllerActions".

Version: 3.1.5, TYPO3 10.4.9
![Screenshot](https://user-images.githubusercontent.com/35603017/95972410-b2fc2000-0e12-11eb-9b1c-44671c1816d9.PNG)

**Comment by featdd** [comment]
Hi @Lurchi96,

thanks for the hint, I fixed it and pushed an update.
See: 7281993c8fb466fc51c7cb816053cb120502b1ba

Greetings
Daniel
