### ISSUE TITLE
BUG: "Glossary preview list"

### ISSUE THREAD

**Issue by cfindeisen** [featdd/dpn_glossary#163]
Hello there,

I found a bug in the content element -> **Glossary Preview List**. There are 3 options to choose from in the CE: "**Newest**", "**Random**" and "**Selected**". My problem revolves around "**Newest**" and I have inserted the CE in my footer to show me the newest terms. But instead of the _newest_ (last) _terms_, unfortunately only the _oldest_ (first) _terms_ come up. My guess is that it is because of the function "**findNewest**" in [**TermRepository.php**](https://github.com/featdd/dpn_glossary/blob/master/Classes/Domain/Repository/TermRepository.php#L94).

Because of **ORDER_ASCENDING** it shows me the _oldest created terms_ but with **ORDER_DESCENDING** it shows me the _newest created terms_.  Here is a short summary to [ORDER_ASCENDING/ ORDER_DESCENDING](https://kb.blackbaud.com/knowledgebase/Article/117098)

Why did you add **ascending** order to the array instead of **descending** order? 
Is **ORDER_ASCENDING** right for the function?

<br>
<br>

→ old function **findNewest**:
```
    public function findNewest(int $limit = self::DEFAULT_LIMIT): QueryResultInterface
    {
        return $this->createQuery()
            ->setOrderings([
                'crdate' => QueryInterface::ORDER_ASCENDING,
            ])
            ->setLimit($limit)
            ->execute();
    }
```
![order_ascending](https://user-images.githubusercontent.com/88704341/128826013-9bc76e7f-c2e6-422d-9506-f080747b27ff.png)

<br>
<br>

→ new function **findNewest**:
```
    public function findNewest(int $limit = self::DEFAULT_LIMIT): QueryResultInterface
    {
        return $this->createQuery()
            ->setOrderings([
                'crdate' => QueryInterface::ORDER_DESCENDING,
            ])
            ->setLimit($limit)
            ->execute();
    }
```
![order_descending](https://user-images.githubusercontent.com/88704341/128826022-d93eaf2b-e9c5-4428-80f0-f71306b6c24c.png)

**Comment by featdd** [comment]
Hi @cfindeisen,

thanks for your issue.
There was no special reason, just a stupid mistake that I never noticed.

Solved in: 5727047fe7c7e02d9424eaceba9ea66478dff69a

Greetings
Daniel
