### ISSUE TITLE
Terms with two words/parts not getting found

### ISSUE THREAD

**Issue by ebene8** [featdd/dpn_glossary#164]
Hi,

I just noticed that only terms with one word/part are getting found but many times a glossary term contains two word/parts. Is this a bug, a missing feature or a misconfiguration on my side? 

I was very surprised because otherwise this extension is great. 

Is there a way to get this going? I need the extension to find a term with "word1 word2".

**Comment by lucmuller** [comment]
It seems to work on my setup, see :
Term : 
![image](https://user-images.githubusercontent.com/1927963/168851139-193d324f-ab46-4017-b28f-4bc6eed2c36c.png)
Input :
![image](https://user-images.githubusercontent.com/1927963/168851347-3437fe6b-b54c-419c-bcd9-794b77fcc519.png)
Output :
![image](https://user-images.githubusercontent.com/1927963/168851077-5e08e4a4-2830-40f9-a257-d8e066a25270.png)

Environment : PHP 7.4, TYPO3 10, and dpn_glossary 4.1.0

**Comment by featdd** [comment]
Hi @ebene8,

I could'nt reproduce this either, so I'll close this for now.

Greetings
Daniel
