### ISSUE TITLE
Plugin throws exception after switching from "Glossarpreview" to "Glossar"

### ISSUE THREAD

**Issue by schlotzz** [featdd/dpn_glossary#168]
Using TYPO3 v10.4.21 and dpn_glossary v4.0 inline parsing of terms just works fine as expected. Following a link to the detail page (now combined with list) throws the following exception.

`
Oops, an error occurred!
The action "show" (controller "Featdd\DpnGlossary\Controller\TermController") is not allowed by this plugin / module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php.
`

Expected behaviour was viewing the detail of the selected, previously clicked term.

### The error can be provoked after the following preparation:
1. Add the plugin "Glossarpreview" and save it.
2. Change the plugin from "Glossarpreview" to "Glossar" and save it.

I did some debugging within the TYPO3 code and it seems, that TYPO3 does not allow the `show` action, but only the last selected action from "Glossarpreview" - in my case `previewNewest`.

### Here is a quick fix that worked with my setup:
1. Delete the "broken" plugin.
2. Add the plugin "Glossar" again **without** switching from "Glossarpreview".

Did I do something wrong? I expected being able to switch between the plugins without any errors.

**Comment by featdd** [comment]
Hi @schlotzz,

I think this issue (#94) is related.

This happens with plugins in general having a flexform with switchable controller actions, it is still loaded and evaluated.
Please delete the whole content element and create a new one that should work.

Greetings
Daniel
