### ISSUE TITLE
Richtext in Tooltips?

### ISSUE THREAD

**Issue by nicodh** [featdd/dpn_glossary#169]
I wonder if it is possible to use Richtext in tooltips. Since right now the tooltip shows only the content from the attribute value, this seems not possible. But since there are so many configuration options, I wonder if it would be possible to achieve that.

Concerning documentation: I could not figure out, what the difference of the various term types is. Is there a documentation showing the differences somewhere?

Thank you for providing this feature rich extension by the way!!
:-)

**Comment by nicodh** [comment]
So far I ended up with dumping the richtext tooltip text urlencoded into an attribute and read that from Javascript ans urldecode it again. What was your solution for avoiding wrong nested tags from Richtext?

**Comment by linawolf** [comment]
We are acutually loading the Texts via Ajax and popover  as our Texts are long and would blow up the page size. Had no problems with wrongly nested tags. Is something wrong about your editors configuration maybe?

**Comment by nicodh** [comment]
Ah ok - if you load textes via ajax it's no problem of course. My first approach was, to render the tooltip text in the fluid template but then I ended up with not allowed tags (like nested <p> etc.)
Thanks for your feedback!

**Comment by featdd** [comment]
Hi @nicodh,

sorry for the late response but it seems you're okay now.
You can always override TCA via TSConfig or custom TCA to enable richtext for the field.
For the extensions base I wanted to keep it simple and add tooltips via CSS and with accessability.

Greetings
Daniel
