### ISSUE TITLE
Method fetchAllAssociative() is not TYPO3 v10 compatible

### ISSUE THREAD

**Issue by PeaceSfiSh** [featdd/dpn_glossary#170]
In version 4.0.0 of EXT:dpn_glossary the Method _fetchAllAssociative()_ is used in the _SlugUpdateWizard_ class.
Unfortunately this method is available from TYPO3 v11. So it's not possible to run the Update Wizard smoothly, in TYPO3 v10.

**Comment by featdd** [comment]
Hi @PeaceSfiSh,

solved this in ec109fceeccfde37853483820c51a9b0d673634a
