### ISSUE TITLE
Problem when using different Pagetypes

### ISSUE THREAD

**Issue by wayheyha** [featdd/dpn_glossary#171]
In ParserService.php on line 194 is a check for pagetype = 0 that aborts parsing if you have a different pagetype.. 
I have a custom pagetype that i need to use in order to load page contents via ajax.. could we maybe get an option to force-enable the parser for certain pagetypes?

Best regards,
Chris

**Comment by featdd** [comment]
Hi @wayheyha,

I could add an option for that, but never tested this myself as the parser needs a full valid html document as input.
So this won't work with html you have encoded in some json or something else...

You may need to instantiate the service by yourself and try to parse your content by desire.
I tried to modularize the parser stuff into a composer library long time ago but forgot about it somehow.
But maybe this could also help, see: https://github.com/featdd/html-term-wrapper

Let me hear your feedback and I will consider to add the option though.

Greetings
Daniel

**Comment by featdd** [comment]
@wayheyha closing this due to lack of feedback
