### ISSUE TITLE
Feature Request: processor for breadcrumbs

### ISSUE THREAD

**Issue by criwe** [featdd/dpn_glossary#173]
Hi,

a feature request: what about adding a processor for breadcrumb-navigations.
have a look at https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/BestPractice/BreadcrumbMenu.html)
Best,
Christoph

**Comment by featdd** [comment]
Hi @criwe,

this was already asked here: https://github.com/featdd/dpn_glossary/issues/51

The link you sent is from the news extension Documentation, not official TYPO3 Core, do you have also official information about this?

Using TypoScript is still legit as far as I know.
But maybe I will consider adding a processor anyway, if I find the time.

Greetings
Daniel

**Comment by criwe** [comment]
Hi Daniel,

sorry for the duplicate...
Maybe https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/ContentElements/CustomDataProcessing.html can help a bit.

Yes, TypoScript is still valid so far, but dataprocessors will be used more in the future (i guess). And things Georg Ringer builds are often best practice.

Best,
Christoph

**Comment by featdd** [comment]
solved in 99d2485dc790c578874333281814c5f85a09a0e9
