### ISSUE TITLE
Installation fails - only white screen

### ISSUE THREAD

**Issue by the-andyman** [featdd/dpn_glossary#178]
First of all, thank you for the extension. 

When installing the current version 4.1.0 via TER on TYPO3 11.5.13 the following error occurs and I get a white page:

`Uncaught TYPO3 Exception: Expected to find class "Featdd\DpnGlossary\Controller\TermController" in file "/html/typo3/typo3conf/ext/dpn_glossary/Classes/Controller/TermController.php" while importing services from resource "../Classes/*", but it was not found! Check the namespace prefix used with the resource. | Symfony\Component\DependencyInjection\Exception\InvalidArgumentException thrown in file /html/typo3/typo3_src-11.5.13/vendor/symfony/dependency-injection/Loader/FileLoader.php in line 224.`

What could be the reason for this and what can I do?

**Comment by featdd** [comment]
Hi @the-andyman,

this looks like a composer autoloading issue, have you required the extension properly and have you tried to delete the vendor and extension folder to rerun composer install?

Greetings
Daniel

**Comment by the-andyman** [comment]
Hi Daniel, 
the extension was installed via the Extension Manager in the backend and not via composer.

**Comment by featdd** [comment]
Okay, have you tried to dump autoload in the maintenance module?

**Comment by the-andyman** [comment]
Ok, after I deleted the autoload and cleared the PHP cache, the Extension installation works! 
Many thanks for the quick help!
