### ISSUE TITLE
EXT:news support detail view ?

### ISSUE THREAD

**Issue by format-gmbh** [featdd/dpn_glossary#179]
Is there any way to parse the page with detail view?

**Comment by featdd** [comment]
Hi @format-gmbh,

the extension always parses the whole page html and doesn't have to know about plugins or content elements.

Maybe have a look into your parser configuration, there you can configure tags which should be parsed or pages which should be excluded and so on.

Greetings
Daniel

**Comment by format-gmbh** [comment]
You are right: it was my mistake. I had excluded the news page from the parser. Thank you very much for your hint.
