### ISSUE TITLE
human readable URLs

### ISSUE THREAD

**Issue by mikeemike7** [featdd/dpn_glossary#180]
Hello,
human readable URLs would be nice. How can I achieve that human readable URLs are output for this extension under Typo3 11.5.x? Whatever I try, the URL is always like https://mysite.com/glossar?tx_dpnglossary_glossary%5Baction%5D=show&tx_dpnglossary_glossary%5Bcontroller%5D=Term&tx_dpnglossary_glossary%5Bterm%5D=7&cHash=06090976b1dd5ccbd07f0c3c285c10e4

**Comment by featdd** [comment]
Hi @mikeemike7,

please have a look into the documentation, there is a full example of how to configure routing for the glossary.

Greetings
Daniel
