### ISSUE TITLE
Pagination / Titles

### ISSUE THREAD

**Issue by criwe** [featdd/dpn_glossary#182]
Hi!
Is there a way to modifiy the pagetitle of paginated pages? I.e. /glossar/B/ should have another pagetitle than /glossar/A/

Thanks!
Best,
Christoph

**Comment by featdd** [comment]
Hi @criwe,

this would propably need a page title provider, I will consider this for the next update.

What kind of title you thought about, maybe "Glossary - [character]"!?

Greetings
Daniel

**Comment by criwe** [comment]
Hi @featdd,
thanks for your reply.

Something like "Title of Glossary-list-page - [character]" would be usefull.

Best regards,
Christoph

**Comment by featdd** [comment]
solved in b92b6a32bb6088efb9d21b8dc1c5294d1e5fc273
