### ISSUE TITLE
PHP Warnings with PHP 8

### ISSUE THREAD

**Issue by criwe** [featdd/dpn_glossary#184]
Hi!
In a TYPO3 11.5.21 (Multidomain-Installation) I see two PHP Warnings when editing an term:

```
PHP Warning

Core: Error handler (BE): PHP Warning: Undefined array key "uid" in //typo3_src-11.5.21/typo3/sysext/core/Classes/Routing/Enhancer/PluginEnhancer.php line 87


PHP Warning

Core: Error handler (BE): PHP Warning: Undefined array key "l10n_parent" in /typo3_src-11.5.21/typo3/sysext/core/Classes/Routing/Enhancer/PluginEnhancer.php line 88
```

When switching back to PHP 7.4, no warnings came up.

The functionality is not affected, is therefore more of an optical flaw.

Best regards,
Christoph

**Comment by featdd** [comment]
Hi @criwe,

I tested this in TYPO3 11.5.22 with PHP 8.0.27 and could'nt reproduce this warning.
The warning also comes from a core class, so maybe it could be a missconfiguration in your instance or something?!

For now I don't see this as an issue in this extension, unless you provide me additional information I will close this issue for now.

Greetings
Daniel
