### ISSUE TITLE
Use lazy-loading for properties of term

### ISSUE THREAD

**Issue by julianhofmann** [featdd/dpn_glossary#187]
I#m focused on the parser part of the extension, less on the plugins... but for the parser, performance can be increased by *not* resolving all relations of the model. For tooltips, there's no need for having `media` or `descriptions`. 
The relations could be loaded via lazy-loading when accessing the property.

Maybe, even a fully simplified model could be used here: no need for medadescription, seotitle,... And for the plugin, this simplified model could be extended... 

Still my use-case: 
1500 terms, 2500 synonyms. So, every avoidable query counts.

**Comment by featdd** [comment]
Hi @julianhofmann,

I merged your pull request here: 738d6c07bba8884271b0d93c7b7f218001416560
Thanks for your work.

Greetings
Daniel
