### ISSUE TITLE
Add TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by featdd** [featdd/dpn_glossary#190]
Add the compatibility to the latest TYPO3 ELTS which will release end of april.

v10 support can be dropped, see [roadmap](https://typo3.org/cms/roadmap)

**Comment by weisgerberm** [comment]
Thanks for your work. I would be happy if it works before the end of April release :)

**Comment by featdd** [comment]
> Thanks for your work. I would be happy if it works before the end of April release :)

Hi thanks, I'll have holidays the next two weeks and hopefully find some time to work on the outstanding issues and compatibility.

I'll prepare some pre release for the compatibility with 12.3 and will update on LTS release asap.

Greetings
Daniel

**Comment by featdd** [comment]
solved
