### ISSUE TITLE
multi word terms are not parsed correctly

### ISSUE THREAD

**Issue by pHilgarth** [featdd/dpn_glossary#195]
Hi,

if there is a term with multiple words, the extension doesnt parse it correctly!

"Not Good" is just replaced with a link to "Not", and the target attribute of that link then is the second word.

--> <a href="/Not" target="Good" />

Would appreciate some advice here or a hotfix.

**Comment by featdd** [comment]
Hi @pHilgarth,

terms with spaces should be no problem and I couldn't reproduce this, how does the slug generated for the term look like?
If the detailpage page is callable I see no problem if the url matches the slug.

Have you done some adjustments on the typoscript configuration for the term rendering?

Greetings
Daniel

**Comment by featdd** [comment]
Hi @pHilgarth,

Ah it's your TypoScript configuration breaking the link rendering, you may take a look at the extensions default settings or look at the [core documentation about Typolinks](https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/Functions/Typolink.html#examples).
I know it's a not very beginner friendly topic, you may ask an experienced colleague.

Also it looks like you missed to configure the detailpage, it is used to render links for detailpages automatically.
So you don't really have to adjust the typolink settings anyway.

I hope I could help.

Greetings
Daniel
