### ISSUE TITLE
Problem with term replacements if there is a character after the term word

### ISSUE THREAD

**Issue by siegtob** [featdd/dpn_glossary#196]
Hello.

I found a new problem.
If I have the term `first/second` and "first" is a glossary entry, then my replacement looks like `first /second`.

This occures always if there is a character after the term word, e. g `first.`.

Actually I haven't found a quick solution for this.
Maybe you?

Greetings,
Tobi

**Comment by featdd** [comment]
Hi @siegtob,

I can't reproduce this, there should'nt be any space added if the term is wrapped.
Do you have any other html manipulation or optimization runnig?

Greetings
Daniel

**Comment by siegtob** [comment]
Yes I`ve there a manipulation running, but I can't see that this causes the error.
Ok, I'll have another look at it - your info that you can't reproduce it helps me to enclose the problem.
