### ISSUE TITLE
Warnings in the log

### ISSUE THREAD

**Issue by SirRuddy** [featdd/dpn_glossary#199]
Got the following warnings in the log:
11:16:48		[0]	warning	php	Core: Error handler (FE): PHP Warning: Undefined array key "**disableParser**" in /html/typo3/typo3conf/ext/dpn_glossary/Classes/Service/ParserService.php line 192	
11:16:48		[0]	warning	php	Core: Error handler (FE): PHP Warning: Undefined array key "**parsingTags**" in /html/typo3/typo3conf/ext/dpn_glossary/Classes/Service/ParserService.php line 180	
11:16:48		[0]	warning	php	Core: Error handler (FE): PHP Warning: Undefined array key "**parsingExcludePidList**" in /html/typo3/typo3conf/ext/dpn_glossary/Classes/Service/ParserService.php line 178	
11:16:48		[0]	warning	php	Core: Error handler (FE): PHP Warning: Undefined array key "**parsingPids**" in /html/typo3/typo3conf/ext/dpn_glossary/Classes/Service/ParserService.php line 176

In the Constants (root) I made the following settings:
plugin.tx_dpnglossary.settings.detailPage = 298
plugin.tx_dpnglossary.settings.disableParser = 1
plugin.tx_dpnglossary.persistence.storagePid = 299
plugin.tx_dpnglossary.settings.parsingExcludePidList = 298

At first I thought it depended on empty constants, but after adding a number to "parsingExcludePidList" the warnings still occur.

Using:
Typo3: 11.5.28
PHP version: 8.1.13
dpn_glossary: 5.0.3

**Comment by featdd** [comment]
Hi @SirRuddy,

have you also added the extension TypoScript to your template? (not only the constants)

Nevertheless the warning is something I will take care of, but for you it seems the TypoScript Setup of the extension might be missing.

Greetings
Daniel

**Comment by SirRuddy** [comment]
Hi @featdd 

Thank you for the quick response. Yes, I have done that. The extension is running without any problems. I only became aware of the errors in the log.

Kind regards
Karsten

**Comment by featdd** [comment]
Hi @SirRuddy,

I couldn't reproduce this partly and optimized it here: 242275cab7dbc679bea6b8e229cd802bd3e1139d

Greetings
Daniel
