### ISSUE TITLE
Links in term mode 'Link' do not lead to the defined page

### ISSUE THREAD

**Issue by projektil-werbeagentur** [featdd/dpn_glossary#200]
Hi,

as of version 4.2.0, clicking on a parsed link does not lead to the page defined with the term, instead you remain on the page with the link and the term is appended to the URL with # as an anchor:
<img width="912" alt="Bildschirmfoto 2023-08-22 um 12 09 27" src="https://github.com/featdd/dpn_glossary/assets/121170981/1c697db6-025b-4ad0-b60a-719304d419d4">
<img width="655" alt="Bildschirmfoto 2023-08-22 um 12 10 18" src="https://github.com/featdd/dpn_glossary/assets/121170981/45d5f3cf-58e0-4387-b2df-fc946d2eec7f">

With version 4.1.0 the linking works as expected.

Using:
Typo3: 11.5.30
PHP version: 8.0.29
dpn_glossary: 4.1.0, 4.2.0, 5.0.3

**Comment by featdd** [comment]
Hi @projektil-werbeagentur,

sorry for the late reply, is this still the case?
Have you changed something on the termWrap TypoScript?

Greetings
Daniel

**Comment by PeterProell** [comment]
I can confirm this. Just hit the same problem.

**Comment by featdd** [comment]
Hi @projektil-werbeagentur & @PeterProell,

I finally managed to fix this, I almost went crazy thinking of a TypoScript issue but it was completely fine.
The introduction of the ParserTerm removed the term link from the content object data array... 🤦‍♂️

solved here: 9140e9b7f99ec8a22f9e94908b3e76c7d7823cef

I will prepare an update soon, thanks for your patients.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @projektil-werbeagentur & @PeterProell,

I optimized this even a bit further with simply using the slug for the anchor link, making at also configurable.
See: ed4bec5049a5261354ed8c808877cf78906d7d7b

Greetings
Daniel
