### ISSUE TITLE
Undocumented breaking change setup.txt -> setup.typoscript (v4 -> v5)

### ISSUE THREAD

**Issue by nhovratov** [featdd/dpn_glossary#210]
The TypoScript + constants files have been renamed to the new file ending `.typoscript`. If extensions included them via `@import` this will fail now for them. Would be a nice hint to have in the changelog. Otherwise you have an error in the frontend and don't know why.

**Comment by featdd** [comment]
Hi @nhovratov,

thanks for the feedback and sorry for you having some troubles with this.
While this is a general TYPO3 change in the newer versions I added a small hint in the changelog, if someone else is struggling with this edge case.

Solved here: 650a8624ceafe637d01fbcf0cacabaae60850b16

Greetings
Daniel
