### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by ben-mckenzie** [featdd/dpn_glossary#211]
Please update the PHP platform requirement to include PHP 8.3

**Comment by featdd** [comment]
Hi @ben-mckenzie,

thanks for the issue, I just tested the extension and increased the required version here: 62e022e215570a0135f58ccfac08e44af3112315

I will prepare a TER release later.

Greetings
Daniel

**Comment by ben-mckenzie** [comment]
Sorry to bring this back, but it looks like composer is still having issues with this platform requirement when updating:

```- featdd/dpn-glossary v5.2.1 requires php >=8.0 <=8.3 -> your php version (8.3.1) does not satisfy that requirement.```

I'm guessing '<= 8.3' only includes 8.3.0 and below.

**Comment by featdd** [comment]
Hi @ben-mckenzie,

yes, I've had set config platform in my composer.json and got no error and thought it was okay...
Just released an update with the fixed version constraint.

Greetings
Daniel
