### ISSUE TITLE
Term-name is linked to part page (term-mode link)

### ISSUE THREAD

**Issue by Tobias-Gl** [featdd/dpn_glossary#214]
Hello, with the term-mode link, the term-name on the target page is linked by the parser and not excluded. This means that the term refers to itself on the corresponding target page.
With the term-mode normal, the corresponding term-name on the detail page is not linked.
Is it possible to adjust the behavior of the term-mode link as with the term-mode normal?

**Comment by featdd** [comment]
Hi @Tobias-Gl,

yes I implemented a feature for this here: https://github.com/featdd/dpn_glossary/blob/c832d6464addcae0c3f3d52399bd740454e68aa8/Classes/Service/ParserService.php#L336-L339

You can enable this by enable this settings: `settings.excludeTermLinksTargetPages = 1`
Also have a look in the [documentation](https://docs.typo3.org/p/featdd/dpn-glossary/5.1/en-us/Configuration/Reference.html?highlight=excludetermlinkstargetpages).

Greetings
Daniel
