### ISSUE TITLE
term within quotations marks

### ISSUE THREAD

**Issue by nannione** [featdd/dpn_glossary#215]
If a text on the website frontend uses quotations marks like „50er“,  it will not be converted into a link to the glossary. If i remove the  quotation marks everything works. Is there a way to resolve this issue? I tried to add the quotation marks in the actual glossary record but that did not work either. However if i write ›50er‹ in the text element and the glossary records it works.

**Comment by nannione** [comment]
I added the quotation marks to the constants settings and now it works.

**Comment by featdd** [comment]
Hi @nannione,

glad you found out by yourself, I especially added this option for special chars, because I couldn't just add them all.

Hope you have fun with this extension.

Greetings
Daniel
