### ISSUE TITLE
Priority of original term before synonym?

### ISSUE THREAD

**Issue by nannione** [featdd/dpn_glossary#216]
Hello,

Maybe I don't understand the logic in this case properly:

I have a text with the term "Camp Booty." I create a record in the glossary, and the term gets parsed correctly in the front end. Now, I add the synonym "Booty" to the same record. However, now only the part "Booty" gets parsed.

The expected behavior for me would be: If the original term is found, it should be given priority over the synonym.

I tried workarounds like creating a separate record for "Booty," but for some reason, it gets prioritized over the record for the original term "Camp Booty".

**Comment by featdd** [comment]
Hi @nannione,

there is an option for this "[settings.priorisedSynonymParsing](https://docs.typo3.org/p/featdd/dpn-glossary/5.2/en-us/Configuration/Reference.html)".

You can always feel free to open an issue if you encounter a bug or have a feature request, but please consider to read the [documentation](https://docs.typo3.org/p/featdd/dpn-glossary/5.2/en-us/) first, a lot of stuff is already implemented. 😊

Greetings
Daniel

**Comment by nannione** [comment]
Sorry, i really overlooked this setting.
