### ISSUE TITLE
term with several parts breaks link creation

### ISSUE THREAD

**Issue by tww-developer** [featdd/dpn_glossary#218]
If the name of the term consists of several parts e.g. 'EINS ZWEI DREI' then the rendered Link in Text looks like:  

```
<a href="/glossar/?tx_dpnglossary_glossary[action]=show&tx_dpnglossary_glossary[controller]=Term&tx_dpnglossary_glossary[term]=38#EINS" 
target="ZWEI" title="EINS ZWEI DREI" class="DREI">EINS ZWEI DREI</a>
```

- the first part is used for the anchor 
- the second part is used for the attribute 'target'
- the third part is used for 'class'   

I guess the problem is somewhere in the Typoscript typolink setting, but I can't figure out whats going wrong.  

Tested with newes TYPO3 (12.4.14) and dpn-glossary v5.2.3

**Comment by featdd** [comment]
Hi @tww-developer,

I just tried to reproduce this but was unable to do so, see my generated link:
`<a href="/glossar/begriff/eins-zwei-drei" title="EINS ZWEI DREI" class="dpnglossary link">EINS ZWEI DREI</a>`

Have you altered the default TypoScript for custom adjustments?

Also it looks like you haven't configured the routing for the plugin yet, have a look into the [documentation](https://docs.typo3.org/p/featdd/dpn-glossary/5.2/en-us/Configuration/ConfigureRoutingForTermsAndPagination.html) for this.

Greetings
Daniel

**Comment by tww-developer** [comment]
Hi Daniel,
thanks for your quick respons.
You are absolutely right - on a realy-realy fresh TYPO3 12 everything works as intended. 
So I have to figure out the problem deeper on my clients project... 

Kind regards
Thomas
