### ISSUE TITLE
TYPO3 13.4 support 

### ISSUE THREAD

**Issue by linawolf** [featdd/dpn_glossary#225]
What are your plans? Are PRs welcome?

**Comment by featdd** [comment]
Hi @linawolf,

sorry for the delay, I started working on it but had to deal with some sickness and other plans on the last weekends.
I try to find some time this sunday to finish the new release.

Greetings
Daniel

**Comment by featdd** [comment]
HI @linawolf,

thanks for your pull request but there were some more adjustments necessary and refactorings I did.
I just released the 6.0 version which is compatible with v13.

So this is solved here: 274cb2ff89d1f40d4661fafe19cb1e0631bfc556

Greetings
Daniel
