### ISSUE TITLE
Migrate the documentation to the new rendering

### ISSUE THREAD

**Issue by linawolf** [featdd/dpn_glossary#227]
The sphinx based rendering was turned off.

See https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/Howto/Migration/Index.html

**Comment by featdd** [comment]
Hi @linawolf,

thanks for the hint, didn't see that they changed this.

Solved here: 58a73d9a45825ccf50af45c2e3ec636ad9a039eb

Greetings
Daniel
