### ISSUE TITLE
Error in Typo3 7.1

### ISSUE THREAD

**Issue by Danny-P** [featdd/dpn_glossary#35]
I'm using Typo3 version 7.1 
Yesterday I did a update of this extension to latest TER version (2.2.6)
In the backend everything is okay, but no front ent page gets rendered any more. In apache logfile I can see the following: 
````
[Tue Jun 23 18:25:56.872659 2015] [:error] [pid 13373] [client <IP:Address>:53396] PHP Catchable fatal error:  Argument 1 passed to TYPO3\\CMS\\Core\\Utility\\GeneralUtility::removeDotsFromTS() must be of the type array, null given, called in /srv/www/typo3/htdocs/typo3conf/ext/dpn_glossary/Classes/Service/WrapperService.php on line 103 and defined in /srv/www/typo3/typo3_src-7.1.0/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 1730
````

**Comment by featdd** [comment]
Hay stupid question but did you cleared all your caches?
May also check your typoscript settings...

Hope this helps

**Comment by Danny-P** [comment]
Yes, I cleared all caches. 
But I have seen, that my template has gone broken. I didn't include dpn_glossary any more. After adding it again, all workes fine. 
Sorry for opening this Issue.

**Comment by featdd** [comment]
Hay don't worry to ask if theres trouble with the extension.
I'm always happy to help :-)
