### ISSUE TITLE
List & detail on same page

### ISSUE THREAD

**Issue by itk-sr** [featdd/dpn_glossary#38]
Hi,
is it possible to have a paginated list on the same page as the detail view?
I need it like this: clickable characters on top as tabs, below on the left a navigation with all the terms starting with the current char and on the right the detail view of the current term.

<pre>
A [B] C D ...
--------------------------------------
B term 1   | Description B term 2
[B term 2] |
B term 3   |
...
</pre>

I've already tried to use the list mode pagination for both the tabs on top and the navigation on the left, setting display: none to the terms above and the chars below, but the problem is that if a term is clicked both navs jump back to A. So how can I keep the highlighted char B on top and the terms starting with B on the left while displaying the B term details on the right?
Is it possible to add the currently selected char to the detail view URL?

**Comment by featdd** [comment]
easier!
Just change the template from the list plugin to also render the details of a term.
Ignore the detailview then.

The term details should be loaded lazy by extbase then.

**Comment by itk-sr** [comment]
Thanks for your reply. So I have removed the detail page and added the content from Show.html to List.html. But now the term details are always empty. What am I missing?

**Comment by featdd** [comment]
Details is plural, you can add multiple, you did term.details.0.meaning for example?

**Comment by itk-sr** [comment]
Yes but how do I make sure that the details of the selected term are shown?

**Comment by featdd** [comment]
The detail entity should normally be loaded lazy by Extbase, the plugin you use doesn't make a difference there

**Comment by itk-sr** [comment]
In the Typo3 page tree I have a page (uid=4) with the list plugin and only the list plugin. I added the Show.html content to the List.html template. In the settings I have detailPage=4 and listPage=4.
But if I click on a term on the list page in the frontend the details remain empty, the show action is never called. I added < f:debug>{_all}< /f:debug> to List.html but it only contains settings, detailPage, listmode and the terms array. I can show the details from terms.0 but I need the details from the selected term which should be loaded dynamically, of course.

**Comment by featdd** [comment]
Aaaaah sry now I get what you want to do...

I'm sry but this is only possible if you change the behavior of the plugin(s) and the controller.
I had this once but then you can't configure realUrl for it.
So this won't be available in future...

**Comment by itk-sr** [comment]
Hmm ok... too bad... so I have to find another solution. Thx for your time though. :)

**Comment by featdd** [comment]
you can configure it yourself but you would have to change the extension yourself.
It is possible but I would not recommend except you give a shit about nice url's :-D

**Comment by itk-sr** [comment]
I give... *g*

**Comment by featdd** [comment]
then add the show action to the list plugin actions in the ext_localconf.php
and remove the pageUid argument from the links in the list template.
Should work for you. 

But beware save your changes or make a fork of this repository with an extra branch.
You can't just update then because you need to apply that changes again to the ext_localconf.

**Comment by itk-sr** [comment]
Then I get "Required argument "term" is not set for Dpn\DpnGlossary\Controller\TermController->show."

**Comment by featdd** [comment]
in the controller the argument default has to be null then and an condition has to be added

```PHP
/**
 * action show
 *
 * @param Term $term
 * @param integer $pageUid
 * @return void
 */
public function showAction(Term $term = NULL) {
	if (NULL !== $term) {
		if ('pagination' === $this->settings['listmode']) {
			$this->view->assign(
				'paginateLink',
				PaginateController::paginationArguments(
					$term->getName(),
					$this->settings['pagination']['characters']
				)
			);
		}

		$this->view->assign('term', $term);
	}		
}
```

**Comment by itk-sr** [comment]
Now the Show.html is loaded with no list at all. Does the list plugin need both actions or only the show action?
<pre>
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
	'Dpn.' . $_EXTKEY,
	'Glossarylist',
	array(
		'Term' => 'show'
	),
	// non-cacheable actions
	array(
		'Term' => ''
	)
);
</pre>

**Comment by featdd** [comment]
both...
```PHP
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
    'Dpn.' . $_EXTKEY,
    'Glossarylist',
    array(
        'Term' => 'list,show'
    ),
    // non-cacheable actions
    array(
        'Term' => ''
    )
);
```

**Comment by itk-sr** [comment]
Alright... now first the List.html is loaded and if I click on a term the Show.html without the list. If I add the list to the Show.html I get the details and an empty list.
