### ISSUE TITLE
MaxReplacementsPerPage is not per page but per tag

### ISSUE THREAD

**Issue by sventendo** [featdd/dpn_glossary#44]
Setting MaxReplacementsPerPage seems to limit the replacement of a term with each DOM elemet defined by the html tag. By default this is the p-tag.

Since every page has usually more than one p-tag the setting has almost no effect. There is still a good chance that one term will be replaced multiple times on one page.

Since the parser iterates first over the DOM elements and then within each DOM element over the list of terms it might be tricky to decide if a term has been replaced within a previous DOM element.

Possible solution would be a change in the textParser() function:
Check if there are matches for a term, then make the replacements with the selected limit (maxReplacementsPerPage) and after that unset the term from $this->term. This would avoid further replacements. Should I write a patch for this?

Also, parsingTags is set to p by default. Is there any other tag that would make sense here?

**Comment by featdd** [comment]
if the limit wouldn't be reached the term could net be unset but will be replaced in the next dom ignoring the last replacements.

this is kind of tricky but I have a solution in mind, the term array has to be expanded and each term has to get its individual counter at the beginning. so the callback can decrement the counter etc.

I will fix this asap, thanks for the hint

**Comment by featdd** [comment]
solved in dde61007fd1f12d28568e0026caaeac84dc170d5
