### ISSUE TITLE
maxReplacementsPerPage: term / counter not called by reference

### ISSUE THREAD

**Issue by sventendo** [featdd/dpn_glossary#46]
To make the maxReplacementsPerPage work across multiple DOM Elements the terms should be iterated by reference:

ParserService.php
line 218:
		foreach ($this->terms as &$term) {

line 251:
				$callback = function($match) use (&$term) {

**Comment by featdd** [comment]
huh? should work without reference I think...

**Comment by sventendo** [comment]
I tested on local environment with PHP 5.4. I will do more testing and come back this issue.

**Comment by featdd** [comment]
Any new results?

**Comment by sventendo** [comment]
Hmmm, a debugging test made me originally open the issue. But I reverted my changes when I pulled your latest version and it seems to work fine now. Object iteration should work by reference anyway. I wasn't so sure about the callback function but I stand corrected. Let's close this issue.

**Comment by sventendo** [comment]
I installed the lastest version (2.3.9) and the issue persists.

Adding the hotfix again, mentioned above, the extension works as expected. I also tried only changing one line at a time, but apparently both calls must be made by reference.

Local PHP Version is 5.4, production server is PHP 5.5. Both environments show the same dehaviour.

**Comment by featdd** [comment]
solved in a187b0414079a5d7ce7d9ae33565a0775ef0784e
