### ISSUE TITLE
PerserService: defaultQuerySettings not being used.

### ISSUE THREAD

**Issue by sventendo** [featdd/dpn_glossary#47]
Using $query->statement seems to level out the default query settings. Why not completely use the query builder?

The issue is that the respectStoragePid is not taken into account as it is.

**Comment by sventendo** [comment]
I see, sorting by length of the term name would not be supported by the query builder.

So either do a usort on the result array (might perform bad) or add the pid to the statement.

I personally would go with the usort because the raw statement might potentially give wrong results when using workspaces etc.

**Comment by featdd** [comment]
yeah the raw statement is rude coding style, at that time I thought it was the best way to bet the terms by length.

I will test usort and check the performance or just add the pid to the current statement.

**Comment by featdd** [comment]
solved in b20da126000921090349e2d154c3ed8fa4ef1791
