### ISSUE TITLE
Show glossary name in Breadcrumbs on Detail page.

### ISSUE THREAD

**Issue by Scopestyle** [featdd/dpn_glossary#51]
Hi,

I am trying to have the Glossary extension show the name in the breadcrumbs on the detail page. 
I currently have this code:

```
[globalVar = GP:tx_dpnglossary_glossarydetail > 0]
 
	lib.breadcrumbs.10.1.NO.doNotLinkIt = 0
	lib.breadcrumbs.10.1.NO.stdWrap.crop = 50 | …
 
	lib.breadcrumbs.20 = RECORDS
	lib.breadcrumbs.20 {
		dontCheckPid = 1
		tables = tx_dpnglossary_domain_model_term
		source.data = GP:tx_dpnglossary_domain_model_term|name
		source.intval = 1
		conf.tx_dpnglossary_domain_model_term = TEXT
		conf.tx_dpnglossary_domain_model_term.field = name
		conf.tx_dpnglossary_domain_model_term.htmlSpecialChars = 1
		wrap = <li><span>|</span></li>
		stdWrap.crop = 50 | …
	}
	
[global]
```
It works so far that I'm getting the wrap shown, but it's empty. I couldn't find anything in the docs. 
Any idea what I'm doing wrong?

**Comment by featdd** [comment]
don't you have to pass the uid of the record you want?

**Comment by Scopestyle** [comment]
Thanx for the quick reply!

I'm trying to adjust the code which calls upon the tx_news extension which looks like this:

```
[globalVar = GP:tx_news_pi1|news > 0]
 
	lib.breadcrumbs.10.1.NO.doNotLinkIt = 0
	lib.breadcrumbs.10.1.NO.stdWrap.crop = 50 | …
 
	lib.breadcrumbs.20 = RECORDS
	lib.breadcrumbs.20 {
		dontCheckPid = 1
		tables = tx_news_domain_model_news
		source.data = GP:tx_news_pi1|news
		source.intval = 1
		conf.tx_news_domain_model_news = TEXT
		conf.tx_news_domain_model_news.field = title
		conf.tx_news_domain_model_news.htmlSpecialChars = 1
		wrap = <li><span>|</span></li>
		stdWrap.crop = 50 | …
	}
	
[global]
```
This works for the news extension, from what I understand (read: trying to understand) is there is no uid record being passed in this example, other then "look for the module on this page and give out the name in field: title". Perhaps this only works there, or I'm targetting the wrong tables.

According to the provided example on [this page](http://www.typo3.net/forum/thematik/zeige/thema/73026/?show=1) I should be calling upon 
`[globalVar = GP:tx_extensionKey_pi1|VariableName > 0] `
.. but .. 
`[globalVar = GP:tx_dpnglossary_glossarydetail|name > 0] `
doesn't seem to be doing anything (I looked up in the database that the names are stored in a field called name) but that's probably wrong variable right?

**Comment by featdd** [comment]
take a look at :
```
source.data = GP:tx_news_pi1|news
```

it has to be the name of the plugin (what you will see in the url) there it takes the data from

**Comment by featdd** [comment]
```
source.data = GP:tx_dpnglossary_glossarydetail|term
```

**Comment by Scopestyle** [comment]
Ahh that was exactly it! Thank you so much :+1:

**Comment by featdd** [comment]
you're welcome
