### ISSUE TITLE
Unable to set custom template paths.

### ISSUE THREAD

**Issue by Scopestyle** [featdd/dpn_glossary#52]
Hi @featdd,

I'm trying to set custom template paths so I don't have to edit the original template files. But no matter what I try the plugin only reads the original path.

What I've tried:

- Setting the template paths in the constants-editor in the TYPO3 backend.
- Setting the template paths in an external setup file.
- Setting the template paths in an external constants file.
- Setting the template paths in the setup file in the ext folder (original file)
- Setting the template paths in the constants file in the ext folder (original file)

Still the module only grabs the original files. Tested on 2 separate installations because I think I might be going crazy. Could it be that these paths are accidentally hardcoded somewhere in the plugin? (Also grabbed the latest version from GitHub, did not solve the problem).

Kind regards,

Erik

**Comment by featdd** [comment]
Will make some investigations, tested it myself and got the same problem...
The path is never defined hardcoded or something, have no idea for the moment

**Comment by featdd** [comment]
the constant setting string has a typo...
was: `{$plugin.tx_dpn_glossary.view.templateRootPath}`
should be: `{$plugin.tx_dpnglossary.view.templateRootPath}`

will push an update to TER
