### ISSUE TITLE
Hiding the glossary detail page in url structure

### ISSUE THREAD

**Issue by Scopestyle** [featdd/dpn_glossary#53]
Hey @featdd, 

First off thank you for the fix on the custom templates! Just downloaded the new version and works like a charm! I hope I'm not too annoying but I have one final question, more realURL related.

Currently I have the following part in my realurlconf setup:

```
'fixedPostVars' => array(
 
	'dpn_glossary_Glossarylist' . '_list_RealUrlConfig' => array(
		array(
			'GETvar' => 'tx_dpnglossary_glossarylist[controller]',
			'noMatch' => 'bypass'
		),
		array(
			'GETvar' => 'tx_dpnglossary_glossarylist[action]',
			'noMatch' => 'bypass'
		),
		array(
			'GETvar' => 'tx_dpnglossary_glossarylist[@widget_0][character]',
		),
	),
	'dpn_glossary_Glossarydetail' . '_detail_RealUrlConfig' => array(
		array(
			'GETvar' => 'tx_dpnglossary_glossarydetail[controller]',
			'noMatch' => 'bypass'
		),
		array(
			'GETvar' => 'tx_dpnglossary_glossarydetail[action]',
			'noMatch' => 'bypass'
		),
		array(
			'GETvar' => 'tx_dpnglossary_glossarydetail[term]',
			'lookUpTable' => array(
				'table' => 'tx_dpnglossary_domain_model_term',
				'id_field' => 'uid',
				'alias_field' => 'name',
				'addWhereClause' => ' AND NOT deleted',
				'useUniqueCache' => 1,
				'useUniqueCache_conf' => array(
					'strtolower' => 1,
					'spaceCharacter' => '-'
				),
				'languageGetVar' => 'L',
				'languageExceptionUids' => '',
				'languageField' => 'sys_language_uid',
				'transOrigPointerField' => 'l10n_parent',
				'autoUpdate' => 1,
				'expireDays' => 180
			),
		),
		array(
			'GETvar' => 'tx_dpnglossary_glossarydetail[pageUid]'
		),
	),

	'6' => 'dpn_glossary_list_RealUrlConfig',
	'16' => 'dpn_glossary_detail_RealUrlConfig',
	
 ),
```

This works like it should and gives me a nice SEO friendly URL:
```
http://www.domain.com/glossary/detail/item-name/
```

Because I removed the "detail" name from the breadcrumbs, and detail as a page does not really exist. (Visiting `http://www.domain.com/glossary/detail/` gets you nowhere) I would also like to remove this part from the URL.

Do you have an idea how this could be done? I've tried checking "_Exclude from speaking URL_" on the detail page but that doesn't seem to do anything in this case ...

**Comment by featdd** [comment]
you have to create a seperate page for the details.
It's because of the detailpages name translation in realurl which only can be handled by using a seperate plugin on a seperate page.
