### ISSUE TITLE
HTML output from ParserService is invalid when using conditional comments

### ISSUE THREAD

**Issue by Ducrot** [featdd/dpn_glossary#54]
Example: Include script resource with a conditional comment:

```
page.includeJS {
    html5 = EXT:myextension/Resources/Public/js/html5.js
    html5.allWrap = <!--[if lt IE 9]>|<![endif]-->
}
```

HTML-Output with disableParser = 1:

`<!--[if lt IE 9]><script src="/typo3conf/ext/myextension/Resources/Public/js/html5.js?1394455858" type="text/javascript"></script><![endif]-->`

HTML-Output with disableParser = 0 (the <![endif]--> part is now missing):

`<!--[if lt IE 9]><script src="/typo3conf/ext/myextension/Resources/Public/js/html5.js?1394455858" type="text/javascript"></script>`

I think the problem starts with ParserUtility::protectInlineJSFromDOM($GLOBALS['TSFE']->content). After this function the html looks like this (include line breaks for better reading):

```
<!--[if lt IE 9]>
<!--DPNGLOSSARY<script src="/typo3conf/ext/myextension/Resources/Public/js/html5.js?1394455858" type="text/javascript"></script>-->
<![endif]-->
```

This is invalid html because of a comment block inside a comment block.

**Comment by featdd** [comment]
hm, this is crap for sure.
Will fix that later.

Thx for the hint

**Comment by featdd** [comment]
hm, made some tests myself and could not recreate this...
the method should work properly :-/

**Comment by featdd** [comment]
fixed in 69a54d815fe1eee5d6333d79fe981afb19f63fa5

**Comment by Ducrot** [comment]
The fix is not solving the problem. Please have a look at the following images.

First image shows the regex process before the fix. As you can see, 
`<!--[if lt IE 9]><script ...></script><![endif]-->`
is replaces by
`<!--[if lt IE 9]><!--DPNGLOSSARY<script ...></script>--><![endif]-->`
which ends in invalid html.
![old-version](https://cloud.githubusercontent.com/assets/3525119/13670451/5ba44ce8-e6ca-11e5-8936-5ea9bd852699.png)

After the fix, the regex is too greedy. Everything from
`<script ...></script><![endif]-->`
to
```
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-xxxxxxx-1']);
    _gaq.push(['_gat._anonymizeIp']);
    _gaq.push(['_trackPageview']);
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>
```
is matching.

The result is also invalid html:
```
<!--[if lt IE 9]><!--DPNGLOSSARY<script src="/typo3conf/ext/myextension/Resources/Public/js/html5.js?1394455858" type="text/javascript"></script><![endif]-->
</head>
<body>

<p> SOME TEXT</p>

<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-xxxxxxx-1']);
    _gaq.push(['_gat._anonymizeIp']);
    _gaq.push(['_trackPageview']);
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>-->
```
![fixed-version](https://cloud.githubusercontent.com/assets/3525119/13670523/c107283a-e6ca-11e5-8df6-6ac94b25082f.png)

I really would like to help you with the regex, but I'm not a pro in that. I can only debug ;-)

**Comment by featdd** [comment]
wtf... I'm sorry will take a look at this :-(

**Comment by featdd** [comment]
hopefully I think this is a satisfying soloution 3ddb0f05feb1977daa61a5c90d146752e3de34b8

**Comment by Ducrot** [comment]
THX, it works!
