### ISSUE TITLE
composer error: [ErrorException] Undefined index: conflicts 

### ISSUE THREAD

**Issue by Gitsko** [featdd/dpn_glossary#56]
Hello,

i have since version 2.3.16 a composer error:

>   Installing typo3-ter/dpn-glossary (2.3.18)
  Downloading: 100% 
  [ErrorException]
  Undefined index: conflicts

With the version 2.3.16 work the composer update.

**Comment by featdd** [comment]
I tried out a few times but cant reproduce this error :-/
