### ISSUE TITLE
Fatal error: Arrays are not allowed in class constants

### ISSUE THREAD

**Issue by Ducrot** [featdd/dpn_glossary#57]
Defining an array constant is new in PHP 5.6. The extension config for PHP is 5.4. So this causes an error for PHP < 5.6:
`const ALWAYS_IGNORE_PARENT_TAGS = array('a', 'script');`
Fatal error: Arrays are not allowed in class constants in typo3conf/ext/dpn_glossary/Classes/Service/ParserService.php on line 49

**Comment by featdd** [comment]
okay will change this to a static array.
But you should consider upgrading php because dependency may will bump to 5.6 in future

**Comment by featdd** [comment]
fixed in 739eeb4c2a3785f6b1b21478a7a6c683e462c0e1
ps: you shouldn't hardcode fixes in a extension, on the next upgrade you may forget something and lose your changes
