### ISSUE TITLE
Textparser Regex doesn't match if a term is next to HTML Tag

### ISSUE THREAD

**Issue by jvmneckar** [featdd/dpn_glossary#58]
Hi,
Typo3 7.6.4, 
dpn_glossary 2.3.15
Term: GmbH
Text Example: `<br>Foo GmbH<br> `

The Text in my Example is not replaced by the parser unless i add a space between the term and the tag (`<br>Foo GmbH <br>`).

Thx

**Comment by featdd** [comment]
hm difficult... the problem are the br tags.
I could match them by say "<br.*>" but now that I see this I think of all other self closing tags...
It's not possible to match them with one expression, that would kill the negative lookahead for not beeing in a child element.

I have a "not so good" soloution but will try to find a better

**Comment by featdd** [comment]
solved in 47d82e74af38f50a7cba9c32020841769c693d5f

**Comment by Fastserv** [comment]
Hi
Sorry for open this again, but I've got the same problem inside <li></li> tags even with space.

Typo3 8.7.3
dpn_glossary 2.7.3

Thank you.
