### ISSUE TITLE
Links to entry detail generate duplicate content

### ISSUE THREAD

**Issue by speedbomb** [featdd/dpn_glossary#60]
Links to an entry detail page from the list page generate urls like _domain.tld/list/myterm/_. Parsed terms on content pages generate ulrs like _domain.tld/list/myterm/123_. The number matches the page id of the referring page.

Since the second url does not have the canonical meta tag set to the first one, this is **potentially duplicate content**.

TYPO3 7.6.4, PHP 7.0.4, dpn_glossary 2.3.19, metaseo 2.0.0

**Comment by featdd** [comment]
hay, please read https://github.com/featdd/dpn_glossary/pull/59

The uid is passed for the backlink in the detailpage

**Comment by speedbomb** [comment]
Sorry, read only the title part and that didn't contain my concerns.

The backlink thing is very useful, but i would assert, that most web project try not to produce duplicate content. So, a canonical meta tag set by default would be the right decision in my opinion.

**Comment by featdd** [comment]
If you want to get rid off the uid you could copy the realUrl conf and just bypass the getvar.

I didn't found out a better technical way to implement the backlink feature, and in the cases I needed the glossary, users expect getting back to the page they're coming from...

**Comment by speedbomb** [comment]
You misread my comment. I like your way to offer a backlink. I only wish, the page http://domain.tld/list/myterm/123/ would habe the following tag in the html head area:
`<link rel="canonical" href="http://domain.tld/list/myterm/">`

**Comment by featdd** [comment]
ah sry, I don't know if it is to expect for an extension to manipulate the header of a page.
Will have to make some investigation and may offer this as an optional feature

**Comment by speedbomb** [comment]
Great to hear that! Thanks.
