### ISSUE TITLE
Will there be a feature to parse the field name_alternative?

### ISSUE THREAD

**Issue by speedbomb** [featdd/dpn_glossary#61]
Hi, are there plans to implement the parsing of alternate terms for an entry? In some languages (e.g. German) there exist many synonyms and adjectives.

**Comment by featdd** [comment]
hi, there are no plans yet.

Only the name is used in the parsing right now and if you have multiple meanings for a term you can add multiple descriptions.

Or did you mean something else and could give me an example of what you meant?

**Comment by speedbomb** [comment]
Hi featdd,
sorry for my poor English. I'll try to explain it by an example:

The term _Magie_ (magic) has several synonyms in German, like _Zauberei_, _Hexerei_ and so on. Additionally there can exists lots of adjectives for the noun, like _magisch_, _magische_, _magisches_, _magischer_, ...

Apart from data redundancy it's very labour-intensive to maintain the terms.

**Comment by featdd** [comment]
hm that's what you mean...
Would be possible I think, but this would need a _synonym_ entity for a nice inline field to add them to a term

**Comment by mlandermann** [comment]
hi featdd,
we have the same issue.
it's the same with singular and plural, declined terms as well as synonyms and adjectives, I think an alternate field for synonyms etc. should be the solution. Would you develop that feature? Or would you give us a little roadmap?
This feature would defintely be an upgrade.
Thank you in advance.

**Comment by featdd** [comment]
I think another entity which you can add inline to the term, like the multiple descriptions, will make sense.
Will make this happen in the next minor update

**Comment by featdd** [comment]
Work is in progress...
Have some thoughts about parsing them, should they count for max replacement or not?
Maybe the best is adding an option for this, but what do you think?

**Comment by featdd** [comment]
solved in 49597b0aba26bbd3b1f00d3de9f6b8d209017322

**Comment by speedbomb** [comment]
> Have some thoughts about parsing them, should they count for max replacement or not?
Maybe the best is adding an option for this, but what do you think?
In my opinion, all alternatives are equivalent to the main term and therefore should count for max replacements.
