### ISSUE TITLE
Tags allowed/not allowed for beeing parsed, functionality complemented with selectors

### ISSUE THREAD

**Issue by solvage** [featdd/dpn_glossary#62]
Please complement the functionality to give selectors like classes or ids to include/exclude parts for parsing.
I have e.g. div#footer, where text elements are places, which should not beeing parsed.

**Comment by featdd** [comment]
excluding implemented in dd20b1eb533f9b02438a7ac635188492c348e4d1

**Comment by featdd** [comment]
I'm still thinking about how to properly implement an explicit including with classes and if this is realy necessary...

**Comment by solvage** [comment]
I got curently a scenario, where this feature would be fine.
Maybe it could be inside of comments, like the search. E.G.:  Content

**Comment by featdd** [comment]
than the excluding should be fine, implementing the explicit including would be hacky by now
