### ISSUE TITLE
Add FE-User access to items

### ISSUE THREAD

**Issue by solvage** [featdd/dpn_glossary#63]
Some entries should be limited to specific fe-users.

**Comment by solvage** [comment]
When you are implementing this, maybe it is a good idea to have start and stop fields for a term included.

Btw: thanks for you quick response for the issues, i am impressed.

**Comment by featdd** [comment]
the start and stop files are there but eventually had been hidden because of a typo in the tca config f458bf18c49d4578fcf29cc3bf06e48fc86e4ce2

**Comment by featdd** [comment]
@solvage how do you thought the access should be handled?

I think if you have a global glossar page and a glossar page in an protected area you should create seperate storages for terms.
Like one for the globals and one for logged in users.
The plugin on the protected page would just configured to use both storages.

didn't saw a kind of usergroup selection on extensions like "news" etc.

what do you think?

**Comment by solvage** [comment]
I think it is better to have it all in one place. This way it is not confusing the visitors - for a better ux. Maybe, the state of an term to be filtered like this, could be accessable by the template. E.g.:
<f:if condition="{term.restricted}">
  <img src="locked.png" />
</f:if>
I could also imagine that the description entries could be limited to fe-usergroups, to have different special informations only for fe-users.

**Comment by featdd** [comment]
hm I always try to have a look how other big extensions handle the stuff.

I saw news has a group select of usergroups, have to look on how stuff is working there...

**Comment by featdd** [comment]
Close this for unnecessarity
