### ISSUE TITLE
Synonyms in list

### ISSUE THREAD

**Issue by solvage** [featdd/dpn_glossary#65]
The synonyms could be shown in the list and linked to the original term.
Status of entry in list determinable by property like
```
<f:if condition="{term.issynonym}">
  <img src="arrow.png" />
</f:if>
```

**Comment by featdd** [comment]
not like your example.
the synonyms are a child entity of terms "{term.synomys}", you have to make a condition with f:count

**Comment by featdd** [comment]
the html dl list expects by standard a term and defintion, I think by default synonyms shouldn't be rendered in the list.

But if you want to render it, it is very easy to overwrite the partial i added here aa2f58ee7af26f4b955fc2c560536bf5ee76a687
