### ISSUE TITLE
TYPO3 7.6.10 crashed after update

### ISSUE THREAD

**Issue by manapo** [featdd/dpn_glossary#67]
Hi,
I just tried to update to the latest version from TER. This crashed the TYPO3 Installation. 
Any suggestions?
Thanks,
Manfred

![image](https://cloud.githubusercontent.com/assets/21084312/17741900/2b77db0a-649e-11e6-8d67-81de069fdae5.png)

Removing the extension manually helped. After that it was possible to install it again but that leads in the same error...

**Comment by featdd** [comment]
this happens if no configuration was added in the template for the page.
There were missed some safety fetching this settings, I fixed it here 9da9c4d9ea82a8b368fb76777fbdf2dfd0431b1e
Update 2.5.3 will be available in ~15min

**Comment by manapo** [comment]
Thanks
