### ISSUE TITLE
"parsingPidsExcludePidList" not working for detailpage

### ISSUE THREAD

**Issue by metiny** [featdd/dpn_glossary#68]
Hi Daniel,
i tryed with 2 different installations on 7.6.11 and dpn_glossary 2.5.4:

in constants i try to exclude my detailpage from parsing:
plugin.tx_dpnglossary.settings.parsingExcludePidList = 31

But it dos'nt work. The terms on detailpage (from the field descriptions) are linked again.

in my realurl config, i have:
	'fixedPostVars' =>
	array (
		'30' => 'dpn_glossary_list_RealUrlConfig',
		'31' => 'dpn_glossary_detail_RealUrlConfig',
	),

link in the listpage: .../ext-testbereich/dpn-glossary/detail/begriff1/
link in the detailpage: .../ext-testbereich/dpn-glossary/detail/begriff1/31/	

and if i click this link from the detailpage, i stay on the same page, but the backlink is changing. If i click the new backlink, a error occurs:
{"exception":"exception 'TYPO3\\CMS\\Extbase\\Mvc\\Controller\\Exception\\RequiredArgumentMissingException' with message 'Required argument \"term\" is not set for Featdd\\DpnGlossary\\Controller\\TermController->show.'

Thanks for your help!

**Comment by featdd** [comment]
sry for any problems, solved in 66b930133329a2918e6dc9307827ed7e68d51830
