### ISSUE TITLE
Add short description text below term

### ISSUE THREAD

**Issue by pixelbreit** [featdd/dpn_glossary#69]
Is it possible to add a short description or teaser text below the term in list mode?
The short text could be cropped from the description text.

**Comment by featdd** [comment]
the tooltip is visible but theres no teaser or short description field yet
otherwise just get the first descriptions text and crop it with fluid like this
`{term.descriptions.0.text -> f:format.crop(maxCharacters: 50)}`

**Comment by pixelbreit** [comment]
Great! This works exactly as I wanted.
