### ISSUE TITLE
php support

### ISSUE THREAD

**Issue by Batman777** [featdd/dpn_glossary#70]
Hi Daniel,

will the ext. support higher php versions in the near future. Unluckily I installed your extension and I got white front and backend. **Ofcourse** I had a backup to do a quick rollback via shell :-)

**Comment by featdd** [comment]
Which php verison are you using?

The extension is developed and tested on 7.0

**Comment by Batman777** [comment]
5.6 at the moment

**Comment by Batman777** [comment]
because typo3 6.2 has (as far as I know) problems with 7.0. I got errors in the backend

**Comment by featdd** [comment]
The extension is fully compatible with 5.6, min dependency is 5.4, 7.1 is not yet tested

**Comment by Batman777** [comment]
Well . I will give it another try and let you know

**Comment by orangenpresse** [comment]
I had the same problem. One one Server everything was fine but on the other server (same php version) nothing worked. I found a solution, maybe this works for you also:
https://github.com/featdd/dpn_glossary/pull/72

**Comment by featdd** [comment]
@Batman777 could you test this out?

**Comment by featdd** [comment]
I think its the missing html wrapper for dom...
@orangenpresse same result can be achieved with this I think
`$tempDOM->loadHTML('<?xml encoding="UTF-8">' . '<!DOCTYPE html><html><body><div id="replacement">' . $replacement . '</div></body></html>');`

do you mind testing it for me?

**Comment by orangenpresse** [comment]
@featdd Yep also works on the crash server!

**Comment by featdd** [comment]
it would be nice if you would amend this in your pull request :-)

**Comment by featdd** [comment]
just found another bug, will commit this myself but thanks @orangenpresse hope this helps @Batman777

**Comment by featdd** [comment]
solved in 1a17fe1a323374306dfe30847ea2849387c76e2c
