### ISSUE TITLE
Multi-lingual

### ISSUE THREAD

**Issue by m-ela** [featdd/dpn_glossary#71]
Is is possible to use the dpn_glossary for more than one languages?

**Comment by featdd** [comment]
yes...

It should support the standard typo3 language overlay, or did you had have any kind of trouble?

**Comment by m-ela** [comment]
Oh great - but I can´t find a language flag to select a language...
![image](https://cloud.githubusercontent.com/assets/22912721/19479491/48d3e6ce-9547-11e6-960b-9fb5aeb093f3.png)

Is there another way to use other languages?

**Comment by featdd** [comment]
did you create a translation for the page/storage in the language you want to translate to?

**Comment by m-ela** [comment]
yes, I did.
![image](https://cloud.githubusercontent.com/assets/22912721/19480988/c247214c-954c-11e6-83ec-ccda57de90bd.png)

Do you have some other Ideas?

**Comment by featdd** [comment]
and also checked the localization view mode?

at least you should be able to select the terms language in the term itself, or create a translation etc

**Comment by m-ela** [comment]
Localization view mode is checked.
When I copy the term I can select a other language, but it would be a chaos width 7 languages...

**Comment by featdd** [comment]
I understand and will investigate this

**Comment by featdd** [comment]
solved in 4027553e74a71d255de6275d8bfdfbc3ef4de057
