### ISSUE TITLE
The last TER version of this extension is not compatible with TYPO3 CMS 6.2

### ISSUE THREAD

**Issue by leonmrni** [featdd/dpn_glossary#77]
The last version of this extension in the TER is not compatible with TYPO3 CMS Version 6.2.
The IconRegistry Class does not exist in TYPO3 CMS 6.2:
- https://github.com/TYPO3/TYPO3.CMS/tree/TYPO3_6-2/typo3/sysext/core/Classes/Imaging

You use the class in the ext_localconf.php file:
- https://github.com/featdd/dpn_glossary/blob/master/ext_localconf.php#L50

**Comment by featdd** [comment]
solved in af6f69242564c6e01f0a2b66ea7d7233e697c3f8

Update is up to TER, thx for the issue
