### ISSUE TITLE
Problem with typolink and dataWrap

### ISSUE THREAD

**Issue by DoYouRockBaby** [featdd/dpn_glossary#78]
Hello guys !

(first sorry for my english, it could be incorrect)

I have a little, it would be very cool if you could help me to solve it.

I'm trying to display my annotation with typolink but i want to add some tags around the link, i simply did this with typolink :

![capture](https://cloud.githubusercontent.com/assets/16799566/21775691/5e916e0a-d697-11e6-9eea-2f71e3ecc0fc.PNG)

The problem is that if i keep the span tags, my typolink doesn't render (bu i have my tags in frontend view).

If i remove the tags, the typolink is working fine.

My team notified that this issue happen still version 2.5.6.

Thanks by advance

**Comment by featdd** [comment]
someone already mentioned that to me, but thanks for the issue so it's more official.
I tested it and had no idea yet why the typolink won't render if dataWrap is used...

I'm currently have not much time to find a solution yet, but I'm on it.

**Comment by featdd** [comment]
just found the problem, which isn't typoscript itself.

its the "domTextReplacer" I use to replace parsed text elements in html, which iterates over childnodes. But I missed that the children have to be iterrated recursive, this results in the missing link which is just forgotten by the dom while replacing...

**Comment by featdd** [comment]
solved in 7330f3200de1078e13d6197fb118e281b20aacdf
