### ISSUE TITLE
TYPO3 7.6.15 - List-Site Error

### ISSUE THREAD

**Issue by ses** [featdd/dpn_glossary#79]
HI, i have a Error on the List-Site:

> The default controller for extension "DpnGlossary" and plugin "Glossarylist" can not be determined.

**Comment by featdd** [comment]
Did you try to delete and readd the plugin? cleared all caches typo3temp etc.?

**Comment by ses** [comment]
all is fine!

**Comment by featdd** [comment]
Delete the plugin and readd it or something, do you use realurl or something which could conflict with the extension params etc.?

**Comment by ses** [comment]
nop, i dont us now realurl (its a dev TYPO3 system)
i delete the plugin for 2 times. And i add the plugin list for more than 2 time :( dont work.
can i send u the dev-link ?

**Comment by featdd** [comment]
yep, send me an email dorndorf@featdd.de

will take a look at this on the weekend

**Comment by featdd** [comment]
update and cleared cache solved the problem
