### ISSUE TITLE
Problem with Multiple languages

### ISSUE THREAD

**Issue by Scopestyle** [featdd/dpn_glossary#80]
Hey!

I have a few problems regarding my setup with multiple languages.

**Current setup:**
- Using the latest plugin version (2.6.11 ) on a TYPO3 7.6.15 installation
- Original Language (0) is German, Translated (1) is English.
- Using the default templates for testing. 

**Problem:**
- Unable to view translated content in the detail page. Below the headline "descriptions of the term:" in the English version no tranlated content gets rendered. Content is there in the backend.
- Unable to switch languages, when I use a language navigation menu, I am getting a the following error:

> #1298012500: Required argument "term" is not set for Featdd\DpnGlossary\Controller\TermController->show.

Kind regards,

Erik

**Comment by featdd** [comment]
I have to test your first case but didn't expierienced that behaviour in the past.

The last problem you mentioned is maybe the missing of some typscript configuration for your language menu.
It doesn't know about any arguments, This also happens on news or any kind of extension having an extra detailpage and passing an required argument.

Greetings
Daniel

**Comment by Scopestyle** [comment]
Hi @featdd, we located the issues and you where right about the typoscript configuration. We did have a part that was missing in the language menu causing the error when switching languages!

As for the part where no translation was visible, this was because it wasn't possible to localize the original description. We fixed this by changing the following:

In: `/Configuration/TCA/tx_dpnglossary_domain_model_term.php` we changed the _descriptions_ appearance from

	'descriptions' => array(
		'exclude' => 0,
		'label' => 'LLL:EXT:dpn_glossary/Resources/Private/Language/locallang.xlf:tx_dpnglossary_domain_model_term.descriptions',
		'config' => array(
			'type' => 'inline',
			'foreign_table' => 'tx_dpnglossary_domain_model_description',
			'foreign_field' => 'term',
			'foreign_label' => 'meaning',
			'minitems' => 1,
			'maxitems' => 9999,
			'appearance' => array(
				'newRecordLinkTitle' => 'LLL:EXT:dpn_glossary/Resources/Private/Language/locallang.xlf:tx_dpnglossary.new_description',
				'useSortable' => 1,
			),
			'behaviour' => array(
				'localizationMode' => 'select',
				'localizeChildrenAtParentLocalization' => true,
			),
		),
	),

to

	'descriptions' => array(
		'exclude' => 0,
		'label' => 'LLL:EXT:dpn_glossary/Resources/Private/Language/locallang.xlf:tx_dpnglossary_domain_model_term.descriptions',
		'config' => array(
			'type' => 'inline',
			'foreign_table' => 'tx_dpnglossary_domain_model_description',
			'foreign_field' => 'term',
			'foreign_label' => 'meaning',
			'minitems' => 1,
			'maxitems' => 9999,
			'appearance' => array(
				'newRecordLinkTitle' => 'LLL:EXT:dpn_glossary/Resources/Private/Language/locallang.xlf:tx_dpnglossary.new_description',
				'useSortable' => 1,
				'showSynchronizationLink' => 1,
				'showPossibleLocalizationRecords' => 1,
				'showAllLocalizationLink' => 1
			),
			'behaviour' => array(
				'localizationMode' => 'select',
				'localizeChildrenAtParentLocalization' => true,
			),
		),
	),

Now the original text shows and can be localized for translation, this was not possible before :smile:

Kind regards,

Erik

**Comment by featdd** [comment]
oh okay, thanks for the investigating

would you be this kind making a pull request so I can merge this properly :-)
