### ISSUE TITLE
change headline of detailheadline or listheadline

### ISSUE THREAD

**Issue by Pavenstaedter** [featdd/dpn_glossary#82]
Hi Daniel,

is there any possibility to change or delete the detailheadline or listheadline by configuration?
I found the words  in the xlf-file and I could uncomment the h1 intemplates/term/...

But I dont want to touch the source of your extension.

Thanks a lot
Volker

PS: Schönes Wochenende

**Comment by Pavenstaedter** [comment]
Hi Daniel,
ok - I should copy the templatefiles to fileadmin and make changes there.
But a way to change the text?


cu
Volker

**Comment by featdd** [comment]
Hi @Pavenstaedter just copy the templates and setup a new templateRootPath over typoscript.
Then you can edit the template and headline as you like.

How familiar with TYPO3 have you been yet?
