### ISSUE TITLE
RealURL support?

### ISSUE THREAD

**Issue by criwe** [featdd/dpn_glossary#83]
Hi!
Thx for maintaining this extension!

Questions: is there a documentation about getting speeing urls via RealURL?
Automatic configuration doesnt work.

Thx!
Best
Chris

**Comment by featdd** [comment]
Hi Chris,

the configuration is automaticly injected to the realurl conf array if realurl is installed and enabled.
You just have to add the configuration key in your fixedPostVars, see [here](https://docs.typo3.org/typo3cms/extensions/dpn_glossary/Configuration/Index.html)

Greetings
Daniel

**Comment by featdd** [comment]
I always like to help, this is open source and my hobby so no paid hiring necessary.

Maybe just send me your realurl conf, do you have any exceptions or logs?

**Comment by criwe** [comment]
Hi Daniel,
thx for your offer! The problem disapeared in a strange way. I´ve added some more terms and only the first I´ve added has the URL-problems... after clearing the RealURL-Cache a view times, everything works fine :-)
Best
Chris
