### ISSUE TITLE
Add possibility to get term as title

### ISSUE THREAD

**Issue by criwe** [featdd/dpn_glossary#84]
Hi!
Featurerequest: Add possibility to get term as title on detailpage :-)

Best,
Chris

**Comment by featdd** [comment]
Hi,

you can achieve this over typoscript

**Comment by featdd** [comment]
not testet but this should to the trick :-)

```
temp.termTitle = RECORDS
temp.termTitle {
  source = {GP:tx_dpnglossary_glossarydetail|term}
  source.insertData = 1
  tables = tx_dpnglossary_domain_model_term
  conf.tx_dpnglossary_domain_model_term >
  conf.tx_dpnglossary_domain_model_term = TEXT
  conf.tx_dpnglossary_domain_model_term.field = name
}

page.headerData.5 >
page.headerData.5 = COA
page.headerData.5 < temp.termTitle
```

**Comment by criwe** [comment]
Cool, works perfect! Thx a lot!
Do you have an amazon-withlist?
Best,
Chris

**Comment by featdd** [comment]
Always glad to help, and yes I have one but don't know what's on it.

But as I said before the support is free 😅

**Comment by featdd** [comment]
@criwe Added the snippet to the documentation by the way
https://docs.typo3.org/typo3cms/drafts/github/featdd/dpn_glossary/Configuration/ExampleTypoScriptSetup/Index.html#add-term-as-page-title

**Comment by criwe** [comment]
Hi! Ok, great!

Maybe you want to add the following. It adds the Metadescription out of the description, strips html and shortens it to 156:

temp.termMeta = RECORDS
temp.termMeta {
  source = {GP:tx_dpnglossary_glossarydetail|term}
  source.insertData = 1
  tables = tx_dpnglossary_domain_model_description
  conf.tx_dpnglossary_domain_model_description >
  conf.tx_dpnglossary_domain_model_description = TEXT
  conf.tx_dpnglossary_domain_model_description.field = text
  conf.tx_dpnglossary_domain_model_description.crop = 156 | ... | 1
  conf.tx_dpnglossary_domain_model_description.stripHtml = 1

}

Best,
Chris
