### ISSUE TITLE
output glossary name and synonym

### ISSUE THREAD

**Issue by pixelbreit** [featdd/dpn_glossary#85]
Hi, in issue #51 is an example how to output the glossary name. 
Is it also possible to output the name and the related synonym? 

I have tried this way:

````
glossartitel = COA
glossartitel {

  10 = RECORDS
  10 {
    dontCheckPid = 1
    tables = tx_dpnglossary_domain_model_synonym
    source.data = GP:tx_dpnglossary_glossarydetail|term
    source.intval = 1
    conf.tx_dpnglossary_domain_model_synonym = TEXT
    conf.tx_dpnglossary_domain_model_synonym.field = name
    conf.tx_dpnglossary_domain_model_synonym.htmlSpecialChars = 1
  }
  10.wrap = |

  20 = RECORDS
  20 {
    dontCheckPid = 1
    tables = tx_dpnglossary_domain_model_synonym
    source.data = GP:tx_dpnglossary_glossarydetail|term
    source.intval = 1
    conf.tx_dpnglossary_domain_model_synonym = TEXT
    conf.tx_dpnglossary_domain_model_synonym.field = name
    conf.tx_dpnglossary_domain_model_synonym.htmlSpecialChars = 1
  }
  20.wrap = &nbsp;&#124;&nbsp;|

}

# Glossartitel als title-Tag ausgeben
page.headerData.80 >
page.headerData.80 = COA
page.headerData.80 < glossartitel
page.headerData.80.wrap = <title>|</title>
````
Unfortunately the RECORD part 20 does not work. 
Any idea what is wrong?

**Comment by featdd** [comment]
I think the 20 part is missing some where clause pointing to the correct parent term.
Also you may have to limit the query to one for there can be multiple synonyms for a term.

Will have a closer look when I'm home

**Comment by pixelbreit** [comment]
I still can't figure out how this is working.
No idea where my mistake lies.
If i want to limit the query can i still use RECORDS?
Or do i need CONTENT and select? 
But with CONTENT and select i should avoid GP.

**Comment by featdd** [comment]
sorry for not responding so long, did you find a solution?
If so I would appreciate this as a example for the documentation

**Comment by pixelbreit** [comment]
I could not pursue this because of the effort.

**Comment by featdd** [comment]
I will close this as this question is more related to typescript
