### ISSUE TITLE
Problem with Indexed Search Engine

### ISSUE THREAD

**Issue by kristiansteinbrenner** [featdd/dpn_glossary#86]
Hey,

we use the dpn_glossary 2.6.13 on a TYPO3 7.6.16 with the indexed_search 7.6.0.
If we search for words which are in glossary terms, we only see the name of the detailview as title in the results list.

So we often have multiple search results with the same title "singleview" wich is the name for the detailview site on our website.

Maybe you can change this in your extension. Because this has to be done in the PHP-code. Here's a tip that may help: $GLOBALS['TSFE']->page['title'] = $post->getTitle();. Found on http://www.typo3tiger.de/blog/post/extbase-page-title-und-meta-tags-im-controller-setzen.html

Greetings
Kris

**Comment by featdd** [comment]
No this should be done in typoscript, please have a look at the [documentation](https://docs.typo3.org/typo3cms/drafts/github/featdd/dpn_glossary/Configuration/ExampleTypoScriptSetup/Index.html#add-term-as-page-title)
