### ISSUE TITLE
Fatal error in TYPO3 6.2.25

### ISSUE THREAD

**Issue by cyMarvin** [featdd/dpn_glossary#87]
I used the extension in TYPO3 7.6.11 and everything was fine.
Now I tried to integrate it into a TYPO3 6.2.30 installation and got the following error message on detail page:
"Uncaught exception 'TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException' with message 'Could not analyse class:TYPO3\CMS\Fluid\ViewHelpers\MediaViewHelper maybe not loaded or no autoloader?'"
According to https://fluidtypo3.org/viewhelpers/fluid/6.2.0.html the f:media viewhelper is available since fluid/TYPO3 7.5.0.
Please update the extension or its dependencies in the TER.

**Comment by cyMarvin** [comment]
I just noticed that i can not add a file to a term in the backend (T3 6.2.30). It says 'file extension "sys_file" is expected'.

**Comment by featdd** [comment]
I overhasty added the media viewhelper etc. I will drop the 6.2 support soon
