### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by lisardo2** [featdd/dpn_glossary#88]
Hello 
TYPO3 7.6.18, last version of dpn_glossar from TER. After installing the extension i made one glosaary entry. After that i got timeout in the frontend on all pages of the site until i uninstalled dpn_glossar. 
There is no exception nor any message so i cant say whats the reason. Any idea? 
Thanks 
Peter

**Comment by featdd** [comment]
No idea, but are you sure that there are no exception messages were suppressed?
Maybe you'll find something in the logs, somewhere somehow there must be an exception thrown.

**Comment by lisardo2** [comment]
No, there is noch exception. I see in activity control that php-cgi is running mad until max_execution_time is reached. Than the server responses with an server error.

**Comment by featdd** [comment]
That is very strange, unfortunately I have no other idea then to debug it and try to find some endless loop or something :-/

**Comment by lisardo2** [comment]
OK, thank you! I will look forward perhaps i can find more information.

**Comment by featdd** [comment]
I'll close the thread until the problem gets concrete
