### ISSUE TITLE
TYPO3 8.7.0 LTS Support

### ISSUE THREAD

**Issue by SirIsaac-1** [featdd/dpn_glossary#89]
Hello.

When will the extension support the new TYPO3 LTS version?

**Comment by featdd** [comment]
hi, 
as soon as I find some time, 2.7 will be 8.7 compatible

**Comment by SirIsaac-1** [comment]
Awesome! Thank you.

**Comment by SicorDev** [comment]
We're already using it with the 8 LTS. Only problem we experienced was with the Flex for the preview list plugin - it somehow breaks the normal list. Since we're not needing this feature at all we just uncommented that part in ext_tables.php - rest of the extension seems to work fine so far.

**Comment by SirIsaac-1** [comment]
Which version are you using? 2.6.13?

**Comment by SicorDev** [comment]
Latest TER version, yes 2.6.13 indeed.

**Comment by featdd** [comment]
solved in 174d0d3b1e5028fc8be2a91943fe4325c388e177

I tested around and seems to work as normal, please report an issue if you found something problematicly
