### ISSUE TITLE
maxReplacementPerPage not working

### ISSUE THREAD

**Issue by MalathDaThon** [featdd/dpn_glossary#92]
I´m sorry to inform you that maxReplacementPerPage isnt working.
it always replaces all terms, no matter which value is given.

It seems that maxReplacementPerPage is using (and at the same time ignoring) a value of 3 and ignores any other value set in backend.
when the decrease counter reaches 0 ist starts with 2 over again...

i have checked the ParserService, but i cant find the bug...

btw: thanks a lot for the link to page functionality 👍 🥇

**Comment by featdd** [comment]
Oh this shouldn't happen, what TYPO3 version do you use?

**Comment by featdd** [comment]
solved in 59c66cf1f2b1cafe9176f5e3cd4d0f6b687c0dbf

just a missing referencing of the terms and replacement counters in a foreach
