### ISSUE TITLE
2.6.13 last version for 6.2.x  not working

### ISSUE THREAD

**Issue by maltisch** [featdd/dpn_glossary#93]
Im using glossary 2.6.13 on TYPO3 6.2.19
and in Detailview i get following error message:

`Could not analyse class:TYPO3\CMS\Fluid\ViewHelpers\MediaViewHelper maybe not loaded or no autoloader?`

I guess MediaViewHelper ist only in TYPO3 7.6  available or did i miss something?
f:media is used in Properties.html

**Comment by featdd** [comment]
I forgot that the media viewhelper isn't available in 6.2, just remove it from the template

**Comment by maltisch** [comment]
I knew this, but for normal TYPO3 Integrator it is annoying, because 2.6.13 supports TYPO3 version 6.2.
