### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by maltisch** [featdd/dpn_glossary#95]
Add available option for listmode to the documentation in extensionssettings

normal, character, pagination 

know 

> Listmode of the listpage (normal list, character sorted list, alphabeticly paginated list)

**Comment by featdd** [comment]
what?

**Comment by maltisch** [comment]
https://github.com/featdd/dpn_glossary/blob/master/Documentation/Configuration/ExtensionSettings/Index.rst

Options for 
plugin.tx_dpnglossary.settings.listmode = 

are 

pagination or normal or character

and not

plugin.tx_dpnglossary.settings.listmode = alphabeticly paginated list

**Comment by featdd** [comment]
ah 😅 
will change that, thanks.

**Comment by featdd** [comment]
solved in 980f411
