### ISSUE TITLE
List all terms at first visit of list with pagination 

### ISSUE THREAD

**Issue by maltisch** [featdd/dpn_glossary#96]
It would be good, if glossary has an  option to show all entries at the fist visit of the paginated list view. This is good option for glossary with less than 100 entries.

I did it the quick and dirty way and changed PaginateController.php on line 

`$this->query->setLimit(1)->setOrderings(array($this->field => QueryInterface::ORDER_ASCENDING));`

to 

`$this->query->setOrderings(array($this->field => QueryInterface::ORDER_ASCENDING));`

**Comment by featdd** [comment]
Hi @maltisch,

I don't really understand your issue, when using a pagination you want your terms sorted by the first character...

You can still use the normal list or grouped view for smaller glossarys.

Greetings
Daniel
