### ISSUE TITLE
Issue with Classes which are not allowed for the parsing tag

### ISSUE THREAD

**Issue by Fastserv** [featdd/dpn_glossary#97]
I can't get this to work. In Constants Editor I tried to set a comma separated list with classes that should not be parsed.
I tried class,.class,div.class and even div#id but nothing worked for me.

Typo3 8.7.3
Glossar 2.7.3
PHP 7.1.7

**Comment by featdd** [comment]
it should be "class-one,class-two,class-three", then tags defined to be parsed but having one of the named classes should not be parsed

**Comment by Fastserv** [comment]
Thank you that worked for me.
