### ISSUE TITLE
Normal linking instead of glossary item

### ISSUE THREAD

**Issue by criwe** [featdd/dpn_glossary#99]
Hi!
It would be nice, to link to normal pages too. So when creating a new glossary-item you can choose between the "normal" entry (like it has allready) and the link-option. With that option you can link internal/external....
If that would be interessting for a sponsored developlement, drop me a line!
Best,
Christoph

**Comment by featdd** [comment]
this is already implemented in #91

**Comment by featdd** [comment]
@criwe can you explain what you meant with normal pages?
the link option offers a typolink field and wizard where you can also select normal pages?
